### ISSUE TITLE
Pattern: Create a service to grab the video meta data 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1065]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create a service that grabs the video meta data 

> so that I can:
include the video meta data in the executive reports

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Functional specs issue (#1066  )

#### Acceptance criteria
 - [ ] alpha react component within the Patterns storybook
 - [ ] create a feature flag for this component
 - [ ] Include README for the react pattern and corresponding styles

**Comment by RobertaJHahn** [comment]
Meeting notes to breakdown into multiple issues:
1)  Create a service to grab the meta data for the video.  5 points  sprint 20-02
2)  Create an Inline embed (default) version of the video player.  5 points  sprint 20-02
3)  Create the link version of the video component that opens into the Lightbox media viewer.  3 points
4)  Enable the Lightbox media viewer to render the Kaltura embedded player.   8 points  sprint 20-02
5)  Enable the metrics for the video player.  4 different events to track.  Start, play, pause and end  5 points
6)  Swap the default icons in the Kaltura video player with the Carbon icons.  Other Carbon style updates TBD.  Contact Felipe to see whether there is code that we can use.  5 points

Convert this issue to an epic.
