### ISSUE TITLE
Abstract migration

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#1073]
### User story: QA tester
As a QA tester using a Windows PC, I need a way to access the design specs from my Windows PC so that I can conducts QA tests.

### Notes
This epic will first focus on the Template Simplification layout patterns first.

### Acceptance criteria
The following layout pattern specs have been moved, documentations have been updated to point to the respective Abstract link.

- [ ] Table of Contents
- [ ] Card section — simple
- [ ] Card section — with images
- [ ] Content block — mixed groups
- [ ] Content block — segmented
- [ ] Content block — simple
- [ ] Content block — with media
- [ ] Content group — simple
- [ ] Content group — with cards
- [ ] Content group — with pictograms
- [ ] Feature card
- [ ] Lead space

**Comment by RobertaJHahn** [comment]
All of the abstract migration issues were linked to the epic managing the ontology work.  Closing this epic as it is no longer needed.
