### ISSUE TITLE
Pattern:  Create Button Group design specs

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1116]
As an adopter or developer on the DDS team I need to know the design specs for `ButtonGroup` pattern. Currently, the only documentation we have is dev/code.

### Tasks

- [ ] Create a Sketch file with ButtonGroup design and specs
- [ ] Create Box folder for ButtonGroup (if not already there)
- [ ] Add design specs and Abstract version to Box folder 
- [ ] Update any links or documentation that needs ButtonGroup specs

**Comment by wonilsuhibm** [comment]
Duplicate issue. Let's use #1528
