### ISSUE TITLE
Identify next steps and content structure for pattern guidelines

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1180]
#### Description
Now that we have a finalized list of patterns which are going into QA, we need to decide how we will publish the new patterns on the cupcake site.

#### Tasks
- [x] Lara to set up time with Wonil, Jenny, Jacob, Jim to review pattern list
- [x] Team to prioritize patterns for publishing
- [x] Team to review the [patterns publishing process](https://ibm.ent.box.com/notes/565346710895) and align on tasks, timeline.
- [ ] Team to identify new content structure/template if and where needed 
- [ ] Create additional stories to track work for each pattern

#### Additional notes
Issue for creating a publishing timeline already exists [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/65).

**Comment by larahanlon2** [comment]
Last week we (Lara, Jenny, Jacob, Jim) met to discuss this work. We reviewed the patterns ontology and publishing process but we need to keep this in the backlog due to other priorities for Feb release and Jim moving on from IBM.

**Comment by larahanlon2** [comment]
Considering we are no longer getting a content strategist I think we still need this story.
