### ISSUE TITLE
Pattern:  Create Link list design specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#1255]
As an adopter or developer on the DDS team I need to know the design specs for `Link list` pattern.  The link list designs are included in some patterns.  The engineering team would like to create a link list stand alone pattern that can be reused.  An example of the link list is included in the `Content Block - Segmented` designs.

 - Content Block - Segmented [Box link](https://ibm.box.com/s/dgnfrnpaqepbuyifa04aoc091v4cnz3d)
 - Northstar example [standards website](https://www.ibm.com/standards/web/v18/design/lists/)

### Tasks

- [x] Create a Sketch file with the stand alone link list design and specs
- [x] Create Box folder for image - with caption (if not already there)
- [x] Add design specs and Abstract version to Box folder 
- [x] Update any links or documentation that needs image - with caption specs

**Comment by wonilsuhibm** [comment]
The design specs are available here (linked from the read me file): https://ibm.box.com/s/dgnfrnpaqepbuyifa04aoc091v4cnz3d
