### ISSUE TITLE
Hills workshop: gather and create personas

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1646]
DDS team is planning to write Hills. In order to successfully create Hills together, we need research and alignment around core findings and artifacts.

## Tasks
- [x] Lara to review old personas created in 2019
- [x] Lara to identify what we need to update and make changes
- [x] Consider if we need new personas
- [x] Lara to share with DDS leadership for review and approval
- [x] Personas to be shared and reviewed with all DDS members

## Acceptance criteria
All DDS members agree that the personas are accurate for our squad mission.

**Comment by larahanlon2** [comment]
Started [this Mural](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1583774848287?sender=larahanlon9022&key=bd48a751-3ca8-4ef1-a6ad-c003c016dbf1) for adopters and personas.

**Comment by larahanlon2** [comment]
The only persona document in our Research folder is old, inaccurate, and not aligned to our current business priorities. As far as I can see, there is only one persona documented:

<img width="1211" alt="Screen Shot 2020-03-17 at 11 52 45 AM" src="https://user-images.githubusercontent.com/53093550/76874711-f6bf8480-6845-11ea-98b7-98af3c2db2dd.png">

**Comment by larahanlon2** [comment]
Hey @wonilsuhibm about your comment in Mural re: end-user persona:
<img width="303" alt="Screen Shot 2020-03-24 at 11 09 44 AM" src="https://user-images.githubusercontent.com/53093550/77444114-e701ec00-6dc1-11ea-8635-0afa6654ae81.png">

I completely agree that these people are important when it comes to our work and team. 100%. My question is, how do you envision such a **persona** fitting into our workflow and how would we go about documenting. 

We could...
1. Create 1 generic "the digital IBM customer" who comes to IBM.com to find a solution.
2. Create multiple personas based on our DGC squad personas: a customer who comes to learn about a topic or technology, a customer who comes to chat with a sales rep, a customer who comes to get support, etc. 

I feel that the first option could be too generic and narrow and without any research to base our assumptions on how do we accurately know their pain points, needs, motivations. The second option would require many personas (which we could probably leverage from DGC teams) but we would need to work out how they relate to our work. Thoughts?

The other direction is that we could simply identify/list these many customers that journey across ibm.com and how, in the end, our work helps them. But not create personas for them right now.
