### ISSUE TITLE
Hills workshop: create as-scenario

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#1648]
DDS team is planning to write Hills. In order to successfully create Hills together, we need research and alignment around core findings and artifacts.

## Tasks
- [ ] Lara to create as-is scenario based on adopters journey 
- [ ] Lara to share with DDS leadership for review and approval
- [ ] Lara to share with all DDS members for review and alignment

## Notes
- Do we need two separate as-is scenarios? One for v18/v19a and once for Carbon for ibm.com?

## Acceptance criteria
- All DDS team members review and agree that the as-is is accurate for our squad mission

**Comment by larahanlon2** [comment]
@RobertaJHahn @wonilsuhibm @ljcarot due to all of the Reboot and covid-19 fire drills, I was not able to complete this issue. Sorry.

**Comment by larahanlon2** [comment]
Will need to move this to the backlog due to 1) Reboot priorities 2) shift in Hills workshop date.

**Comment by RobertaJHahn** [comment]
Dup of issue (#2540)  Closing
