### ISSUE TITLE
Visit the Cupcake website roadmap and decided what we need to add to the website for MVP

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#1757]
> As an IBM.com Library website creator,

> I need to take a look of the Cupcake website roadmap with the product owner,

> so that I  know what we are going to work on as the 2020 MVPs.

#### Task
- [ ] Schedule a time to go over the roadmap with Linda and Wonil.
- [ ] Create task issue to update the sitemap if needed

#### Acceptance criteria
- [ ] Have a list of what we are going to work on for the website in 2020.
