### ISSUE TITLE
Guidelines : layout patterns for cupcake website

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#191]
_LARAHANL created the following on Nov 27:_  

 ## User story

As an adopter I need to see examples of good layout design so that I can create a strong user flow and page narrative.

### Notes
Some work in the past are found in [Box](https://ibm.box.com/s/nsvj1pl56dwws8lp0nhzl3n1cc57rbbf)

An example of what this may look like is captured [here](https://ibm.box.com/s/4pijbvnt3mcckxuk9w7ibrset0sfhixn)

### Acceptance criteria
- [ ] Provide a set of layout options
- [ ] Each option should have high level intent and usage mappings (this band is recommended for long reading)
- [ ] Provide some examples of each
- [ ] update 2x grid layout patterns page

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/339_

**Comment by jeffchew** [comment]
_On Nov 27, LARAHANL commented:_
https://www.ibm.com/standards/web/design-guidelines/layout-patterns.html

**Comment by jeffchew** [comment]
_On Jan 07, LARAHANL commented:_
@chsanche here's something you might want to jump in on. There is no current milestone but this page needs some redesign love https://www.ibm.com/standards/web/design-guidelines/layout.html 

Initial thoughts from @Wonil-Suh1 : how can we make this more expressive and exciting? Can we show new examples? Can we improve the layout of this page?

**Comment by jeffchew** [comment]
_On Feb 01, LARAHANL commented:_
Things to consider:

- [ ] recommended top spacing
- [ ] recommended bottom spacing
- [ ] text placement options
- [ ] some common layout options (4-4-4-4, 2-6-6-2, 6-6, etc)
- [ ] common type hierarchy options
- [ ] examples and inspirations
- [ ] DOs and DON'Ts

**Comment by jeffchew** [comment]
_On Apr 10, LARAHANL commented:_
@Wonil-Suh1 here's the Epic I created earlier this year for layout patterns. 

- We could keep this as an epic and create user stories for each task
- or we remove the epic and only focus on individuals issues

**Comment by jeffchew** [comment]
_On Apr 11, Wonil-Suh1 commented:_
@LARAHANL I think we should keep this for now, until we have a good number of patterns. Then we can close this epic and open new issues per case basis. What do you think?

**Comment by jeffchew** [comment]
_On Apr 18, Wonil-Suh1 commented:_
An idea for interactive pattern preview component (moving from #494):

![5ca76780-5a4c-11e9-86db-a348d7aa82a0](https://media.github.ibm.com/user/25726/files/3f973500-61c0-11e9-8443-919a4d9519d7)

**Comment by jeffchew** [comment]
_On Aug 04, Wonil-Suh1 commented:_
Let's make this a bit detached from use cases, and focus on layout options based on grid usage, intent (reading, transactional, level of details, placement on the page).

**Comment by jeffchew** [comment]
_On Aug 06, Wonil-Suh1 commented:_
Per discussion, changing this story to guidelines on cupcake.

**Comment by larahanlon2** [comment]
Closing this epic. It is old and the guidelines for layout patterns v1 are live: https://ibm-dotcom-library.mybluemix.net/patterns
