### ISSUE TITLE
Understanding adopter use of component pages

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#192]
_elraymond created the following on Dec 05:_  

 ## User story

As a designer on Carbon + Digital I need to get a better understanding of how our adopters are using the component pages on the site so that I can improve on the component experience.

## Deliverables

- survey sent to adopters
- results from survey
- synthesized findings
- next steps & reccomentations

### Notes

This is preliminary research and is done across both teams Carbon & Digital

### Tasks

- [x] proposed survey
- [x] refine survey with Carbon
- [x] refine survey with leadersip
- [x] build survey
- [x] send out survey & collect results
- [ ] synthesize data & findings
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/370_

**Comment by jeffchew** [comment]
_On Dec 05, elraymond commented:_
All survey back purpose information, plan of attack & questions are here: https://ibm.box.com/s/r6y2zmgzrirakncusojfcox651yfbspd

**Comment by jeffchew** [comment]
_On Dec 17, elraymond commented:_
built survey out in Survey Monkey, but need a paid account because of the logic and number of questions. Got access to Verint and going to use that as the survey tool for this

**Comment by jeffchew** [comment]
_On Dec 21, elraymond commented:_
survey created, going to send out January https://survey.vovici.com/se/05A1DD045432E8B8

**Comment by jeffchew** [comment]
_On Dec 21, elraymond commented:_
Content for survey communications:

"The holidays may be over, but you can still spread cheer by telling us about **how you use component pages** on the design system site. Take [this **5 minute survey**](https://survey.vovici.com/se/05A1DD045432E8B8) to ensure a better component page experience is in your future."

**Comment by jeffchew** [comment]
_On Dec 21, elraymond commented:_
@Wonil-Suh1 can you please review survey and survey comms so that I'm good to go come Jan 2nd

**Comment by jeffchew** [comment]
_On Dec 21, Wonil-Suh1 commented:_
- The tab labels - do we know if users understand what they are, what to expect?
- Should we ask what the pain points are, what other similar sites they use?

**Comment by jeffchew** [comment]
_On Jan 04, elraymond commented:_
reviewed survey with Ben, ready to send
https://survey.vovici.com/se/05A1DD045432E8B8
will send out on Monday

**Comment by jeffchew** [comment]
_On Jan 07, elraymond commented:_
content options for slack:

"Happy 2019 everyone 🎉

The Design system team is excited to start this year off by improving the experience of our website component pages. We're looking to learn everything about your experience with our component pages thus far.

Please fill out this 3 minute survey to make sure your voice is heard: https://survey.vovici.com/se/05A1DD045432E8B8"


"Happy 2019 everyone 🎉

Have you been itching to give us feedback on our website component pages? Good news, now is the time! We're kicking off the year by working to understand how you use our component pages and how we can make your experience that much better.

Please fill out this 3 minute survey to make sure your voice is heard: https://survey.vovici.com/se/05A1DD045432E8B8"

**Comment by jeffchew** [comment]
_On Jan 08, Wonil-Suh1 commented:_
It looks good to me. The design of the survey is not IDL, but I guess we will get to that next year. :) Thank you Erica and Ben.

**Comment by jeffchew** [comment]
_On Mar 04, elraymond commented:_
total # of surveys completed: 55

Survey questions have been put into matrix here by filtering different audience groups and different systems used: https://app.mural.co/invitation/mural/ibm14/1548774389793?sender=elraymond&key=81a5eb64-08a7-4cb8-a296-3c9d2dd9ae3f

Working with @trtate from Carbon to synthesize information to form insights and recommendations based on all of these answers

**Comment by jeffchew** [comment]
_On Mar 08, elraymond commented:_
synthesis is documented here: https://app.mural.co/invitation/mural/ibm14/1548774389793?sender=elraymond&key=81a5eb64-08a7-4cb8-a296-3c9d2dd9ae3f

**Comment by jeffchew** [comment]
_On Mar 18, chsanche commented:_
@Benjamin-Hansen1 Can you take a look at the synthesis from Erica and let me know what you think?
FYI - Components page update task issue for the website is created - #646

**Comment by jeffchew** [comment]
_On Mar 25, Lisa-Lurie commented:_
@Benjamin-Hansen1 Add you comment please!?

**Comment by jeffchew** [comment]
_On May 03, chsanche commented:_
@Olivia-Flory Tagging you here since this is Components related.

**Comment by jeffchew** [comment]
_On Jun 25, chsanche commented:_
@Olivia-Flory and @Benjamin-Hansen1 I think this task can be beneficial to the future build of the new Gatsby website. What do you think? Let me know if you prefer to close it or keep it. 

FYI: Put the "design" label on it as it's a request from Wonil.

**Comment by RobertaJHahn** [comment]
Outdated.  There is a replacement plan for the component pages.
