### ISSUE TITLE
Locale banner prototypes desktop

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#1939]
#### User Story

> As a `[user role below]`:

DDS designer

> I need to:

prepare the prototypes

> so that I can:

test the locale banner design 

#### Additional information

Prepare the prototypes for testing the locale banner

**Tasks**
- [ ] Translate prototype language into German (reach out to designers in Boeblingen Studio)
- [ ] Create screens for Invision or other prototyping tool
- [ ] Add any necessary URLs to UT plan

#### Acceptance criteria
- [ ] Any necessary URLs added to UT plan
 - [ ] Prototypes have been translated in German
 - [ ] Prototypes are in invision or other program for testing
 - [ ] Review with Design team

**Comment by RobertaJHahn** [comment]
Closing as this work is being managed on the Design Ideation board.
