### ISSUE TITLE
Create the "Designer Contribution Guideline" for the wedding cake website

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#199]
_chsanche created the following on Jan 21:_  

 ## User story

As a Digital Design System adopter, I need a way to contribute my design back to the team, so that my design can be added to the Digital Design System and be utilized.

## Deliverables

- Designer Contribution Guideline

### Notes

- We do not currently have any guideline around contribution.
- Resource: Carbon
(for Designer) https://next.carbondesignsystem.com/contributing/designers
(for Add-on) https://next.carbondesignsystem.com/contributing/add-ons

### Acceptance Criteria (defining "done")

- Have the guideline published on the website

### Tasks
- [ ] Create a high-level draft on what we need in the guideline
- [ ] Review with the designers
- [ ] Review with the content team
- [ ] Review with the DDS team
- [ ] Finalize the guideline
- [ ] Post the guideline on the website 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/482_

**Comment by jeffchew** [comment]
_On Mar 06, chsanche commented:_
**Note:** We need to figure out if the contributions from others are for us or for Carbon to handle.

**Comment by jeffchew** [comment]
_On Mar 06, chsanche commented:_
I created a rough draft of the contribution guideline for designers based on what Carbon has and can be view [here](https://ibm.box.com/s/s63murepzh09u9tk42l466szffqkkl0g).


A few findings, there are quite a few repos, guideline, and templates Carbon has. We need to do an audit on what we have then either create one or update ours to make sure we are aligned with Carbon's process and templates.

**Comment by jeffchew** [comment]
_On Mar 06, chsanche commented:_
@Olivia-Flory @Wonil-Suh1 @Lisa-Lurie Tagging you for FYI purpose.

**Comment by jeffchew** [comment]
_On Jun 24, chsanche commented:_
**Update:** This guideline will be published on the new Gatsby website or use the one Carbon has based on the mental model/ website IA decision.
