### ISSUE TITLE
Standardize how we spec / redline our design files

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#200]
_LARAHANL created the following on Feb 07:_  

 ## User story

As a designer on our team I need clear examples and standards for how we should redline our design files so that our developers and adopters receive consistent specifications.

## Deliverables

- Sketch file with spec standards

### Notes

As designers we have different methods of redlining our design files. As a team, these differences can cause confusion or slow down the process because they are not all consistent. 

### Tasks

- [ ] gather examples of spec'd design files from our team
- [ ] identify the most successful redlines (colour, line weight, type size)
- [ ] consider plugins 
- [ ] create one master Sketch file to use as a reference
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/541_

**Comment by wonilsuhibm** [comment]
Spec library, guidelines, and Abstract.
