### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#203]
_LARAHANL created the following on Mar 05:_  

 Let's define some of the commonly used terms from the design perspective so that when designers work with other teams and disciplines we can be clear.

### Batch 1
- These terms defined:
   - [x] Element
   - [x] Component
   - [x] Add-on component
   - [x] Pattern
- Agreed upon by these teams:
   - [x] DGC squads
   - [x] Drupal
   - [x] IDL
   - [x] Carbon

### Batch 2
- These terms defined:
   - [x] Module
   - [x] Band
   - [ ] Layout
   - [ ] Page template
   - [ ] Theme
   - [ ] Page types
- Agreed upon by these teams:
   - [ ] DGC squads
   - [ ] Drupal
   - [ ] IDL
   - [ ] Carbon

### Batch 3
- These terms defined:
   - [ ] Design language
   - [ ] Design system
   - [ ] Discipline
   - [ ] Add-on
- Agreed upon by these teams:
   - [ ] DGC squads
   - [ ] Drupal
   - [ ] IDL
   - [ ] Carbon

## Acceptance Criteria
- [ ] all terms have been defined
- [ ] all terms have been agreed upon by stakeholders
- [ ] have a plan for publishing

## Additional information
[Audit of other IBM design systems](https://ibm.box.com/s/3mdounssaox2lth73fcrc87dtxt2l7vx) 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/610_

**Comment by jeffchew** [comment]
_On Apr 30, larahanlon commented:_
Currently collaborating with Kristen Kogachi to create a team-wide, sharable glossary. See this Boxnote for WIP definitions.

**Next steps:**
- [x] Kristen, Lara, Wonil, Lisa will continue to write definitions that relate to Design at DGC.
- [x] Kristen is aligning with Drupal for their set of definitions.
- [x] We will share our glossary with Carbon for alignment.
- [x] We will share our glossary with IDL for alignment.
- [x] We will share our glossary with DGC for alignment.

**Comment by jeffchew** [comment]
_On May 24, Wonil-Suh1 commented:_
I suggest that we divide this into smaller chunks that we can focus on over sprints. The goal for each batch would be to focus and define the given terms in the batch, and get agreement.

### Batch 1: fundamental building blocks
- [ ] Element
- [ ] Component
- [ ] Add-on component
- [ ] Pattern

### Batch 2: solving complex problems
- [ ] Module
- [ ] Band
- [ ] Layout
- [ ] Page template
- [ ] Theme
- [ ] Page types

### Batch 3: higher level
- [ ] Design language
- [ ] Design system
- [ ] Discipline
- [ ] Add-on

### Sprint 13 and on: let's see where we are and decide.

**Comment by jeffchew** [comment]
_On May 24, Wonil-Suh1 commented:_
Converting to an epic according to the table and will add an issue for each batch so that we can work on each and close them out in sprints.

**Comment by jeffchew** [comment]
_On Jun 06, larahanlon commented:_
🤔 What is the outcome of all of this? Where will this content live? 

Here's some inspirations from InVision!
https://www.invisionapp.com/design-defined/
<img width="1671" alt="screen shot 2019-06-05 at 4 32 18 pm" src="https://media.github.ibm.com/user/220101/files/9deb9780-87af-11e9-8ffd-f77586bd7162">

**Comment by jeffchew** [comment]
_On Aug 20, larahanlon commented:_
- Published Glossary to our DDS [wiki](https://github.ibm.com/webstandards/digital-design/wiki/Design-System-Glossary).
- Shared with Web Simplification team on Wednesday August 14th. Here's feedback from Elliott:

> Team, this looks great. Some nit picky items:
> 1. There has been a sustained debate about this model v. the atomic design model.  Can you please explain the relationship of our stuff to the elements of atomic design so we can avoid that debate again?
> 2. For Core Components, please explain a bit more on the Carbon philosophy of core components, why there are so few of them, etc
> 3. Examples of patterns provided looks more like TYPES of pattern categories, not examples of actual patterns.  e.g. a workflow is a category. I would expect us to then say that Buy is sub-category, and that there are 3-5 patterns for Buying on IBM.com (e.g. 1st time purchase; Add Seats or "Buy More", etc etc.) . I see us go back and forth on the definition of patterns all the time, so I'd like us to get to a tighter definition here.
> 4. Theme.  Why aren't we discussing Expressive and Productive Theme here? That's critical to the new architectural relationship with Carbon.  We have to nail this one and be clear on how it works.
> 5. Module.  Please add more than one description.
> 6. As i'm reading this, it's clear that while this glossary is a great foundation for the team, we need a pictorial representation of a page to more eficiently describe these things, something like "all the things that form a page."
> 7. And finally, let's make sure that we nail the difference between a page and a template.

**Comment by jeffchew** [comment]
_On Sep 03, larahanlon commented:_
@Wonil-Suh1 how do you feel about creating new issues for the next sprint? I think we could address some of Elliott's feedback without too much labor. We've already made a start on defining `module`, `theme`, `band` – they just need some elaboration. We could also tackle `page template` with Web Simplification.
