### ISSUE TITLE
Best practice for the primary and secondary button placement 

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#204]
_chsanche created the following on Mar 07:_  

 ## User story

As a maker, I need to learn where the primary and secondary button placement should be when using them side by side on my .com page.

## Deliverables

- Add button placement best practices to [Button usage page](https://www.ibm.com/standards/web/components/button/usage/). 

### Notes

- Watson has the primary button on the left-hand side and the secondary button on the right-hand side.
![1](https://media.github.ibm.com/user/5181/files/35671e80-40cb-11e9-86e9-e0bbdf0ac0df)

- Carbon has the primary button on the right-hand side and the secondary button on the left-hand side.
![artboard copy](https://media.github.ibm.com/user/5181/files/3e57f000-40cb-11e9-89d6-74ea22e1aa89)
![artboard](https://media.github.ibm.com/user/5181/files/3e57f000-40cb-11e9-8b7d-965743e3c916)

- What we currently have on the Buttons page.
![artboard copy 2](https://media.github.ibm.com/user/5181/files/1075aa00-40d1-11e9-8bec-a961054f4ae9)

### Acceptance Criteria (defining "done")

- Add the button placement guideline on the website

### Tasks

- [x] Reach out to Carbon and IDL team to confirm the usage guideline they have
- [ ] Do a study on what's out there around primary and secondary button placement
- [ ] Work on the best practice draft
- [ ] Take a look with the team (Design review meeting)
- [ ] Share with carbon for feedback
- [ ] Work on revision
- [ ] Add the content to the Button - Usage page 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/616_

**Comment by jeffchew** [comment]
_On Mar 07, chsanche commented:_
**Update on findings:**

Carbon (from Anna)- The primary button on the right-hand side and the secondary button on the left-hand side.

IDL (from Sadek) - No formal guidance. In most of their explorations, they put them directly side by side but that does not always work in every instance.

**Comment by jeffchew** [comment]
_On Mar 07, chsanche commented:_
@Benjamin-Hansen1 I remembered you have done research on this topic before. Can you share your POV or research findings? My goal is to have a guideline (a paragraph will be ideal) for us to add to the button page and make an update to the page based on the outcome.

**Comment by jeffchew** [comment]
_On Mar 07, chsanche commented:_
**FYI:**
We will contribute the guideline back to Carbon.

**Comment by jeffchew** [comment]
_On Mar 11, chsanche commented:_
Watson button placement - The primary button on the right-hand side and the secondary button on the left-hand side.

![screen shot 2019-03-08 at 11 46 21 am](https://media.github.ibm.com/user/5181/files/a63d6c00-4426-11e9-8f96-0d6813d77d13)

**Comment by jeffchew** [comment]
_On Mar 27, Lisa-Lurie commented:_
@chsanche What is this story about exactly- guidelines for button placement? If so, could that be more clear?

**Comment by jeffchew** [comment]
_On Mar 27, chsanche commented:_
@Lisa-Lurie I update the use case for this task issue and let me know if it still confusing?

**Comment by jeffchew** [comment]
_On May 06, chsanche commented:_
A good study for us: **Primary & Secondary Action Buttons by Nick Babich**
https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150

**Comment by jeffchew** [comment]
_On May 28, Wonil-Suh1 commented:_
@Benjamin-Hansen1 can you share the research result here please?

But if I remember correctly, the research shows clearly that the primary button should be placed on the right side.

**Comment by jeffchew** [comment]
_On May 29, Benjamin-Hansen1 commented:_
The Primary CTA goes in the Secondary position. So when buttons are 
left/right, “what you want them to pick”, the primary CTA, goes to the 
right. If top/bottom, primary CTA goes on the bottom. Basically, many 
people don’t even notice the secondary button if it’s in the secondary 
position (which reduces its value), and at the same time, the primary 
button gets the same number of clicks whether on the left or right. 

See http://uxresearch.w3ibm.mybluemix.net/search/?id=13819


Warm regards, 
- Ben 
_____________________________________________________________________________________________________________ 

Ben Hansen
User Research Director - IBM Digital
720.201.6695
Benjamin.Hansen1@ibm.com 
"To measure is to know" - Lord Kelvin




From:   WONIL SUH <noreply@github.ibm.com>
To:     webstandards/digital-design <noreply@github.ibm.com>
Cc:     "BENJAMIN E. HANSEN" <Benjamin.Hansen1@ibm.com>, Mention 
<mention@noreply.github.ibm.com>
Date:   05/28/2019 12:40 PM
Subject:        Re: [webstandards/digital-design] Best practice for the 
primary and secondary button placement  (#616)



@Benjamin-Hansen1 can you share the research result here please?
But if I remember correctly, the research shows clearly that the primary 
button should be placed on the right side.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub Enterprise, or mute the 
thread.

**Comment by jeffchew** [comment]
_On Jun 05, chsanche commented:_
**Placement**

When using two buttons, the recommendation for side-by-side placement is that the primary button should appear to the right of the secondary button. For right-to-left languages, the order will be reversed. When the primary and secondary buttons are stacked top-to-bottom, the recommendation is that the primary button should appear below the secondary button.

**Comment by jeffchew** [comment]
_On Jun 05, chsanche commented:_
@Wonil-Suh1 @Benjamin-Hansen1 Please review the best practice content above and let me know what do you think?

PS: @Olivia-Flory and @larahanlon thank you both for taking a look at the content with me. 👏

**Comment by jeffchew** [comment]
_On Jun 07, Wonil-Suh1 commented:_
This looks good to me. Thanky ou @chsanche !!!

For future iterations:
- How to handle the case when danger button is the primary?
- Recommend using the tertiary button for secondary.
- Sometimes, there is no primary-secondary distinction between the two buttons. Then what?

**Comment by jeffchew** [comment]
_On Jun 07, chsanche commented:_
@Wonil-Suh1 Thank you and good points for the future iterations. 
FYI: Task issue #980 is created for future iteration work.
