### ISSUE TITLE
Review content for lead space page

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#205]
_chsanche created the following on Mar 07:_  

 ## User story

As a DDS designer, I need to make sure our website has the most up to date and relevant information for our users.

## Deliverables

- Update the content to our web pages

### Notes

- Content from https://github.com/carbon-design-system/ibm-dotcom-library/issues/205 is contributed by James F. Pate from the CHQ-SEO team. 

### Acceptance Criteria (defining "done")

- Our Lead Space page content is updated based on the review outcome.

### Tasks

- [x] Have Wonil review the Leadspace page content from James F. Pate and provide a recommendation on what we should add to our page.
- [ ] Create a task issue for mockup creation (if needed).
- [ ] Create a task issue for dev. for review together and work on the update. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/619_

**Comment by jeffchew** [comment]
_On Mar 07, chsanche commented:_
@Wonil-Suh1 Can you share your thought on the contributed content below?

It's for the code guidelines [Lead Space page](https://www.ibm.com/standards/web/components/lead-spaces/).

My main concern is having the title always approved by or determined by an SEO Strategist. Although it's the best practice to do so, are we asking our users to do it as part of the work process? If there's anything, should this be a recommendation instead?

---

## H1 lead-space title
**The lead-space title should be approved by or determined by an SEO Strategist** since it is one of the most important SEO elements on a page. The lead-space title should be a concise statement of the topic of the page containing the main SEO friendly topic for the page. Ideally the features/benefits should be in the subheading so the title of the page is concise and easy to read. **This title should not be used for highlighting case studies, events, other pages, or anything besides the topic of the page.**

**Comment by jeffchew** [comment]
_On May 14, chsanche commented:_
@larahanlon FYI on this task issue existed. 

This is contributed by James F. Pate from the CHQ-SEO team. See #488 for detail.

We need work on the contribution guidelines, of course, so we know how to handle the contributions. 

For now, please take a look at what he has and we need to either:
`A.` accept his contribution and update what you have for the Lead Space 
`B.` we declined the contribution bc it does not meet our user's need, comment on both task issues (this one and #488) then close the task issues.

**Comment by jeffchew** [comment]
_On May 14, chsanche commented:_
@Wonil-Suh1 FYI.

**Comment by jeffchew** [comment]
_On May 15, larahanlon commented:_
@chsanche thank you!

I think he has some good things to consider, which we could include in our guidelines. 
The main thing I question is the opening sentence: **The lead-space title should be approved by or determined by an SEO Strategist.**

Is that true? Do all teams have an SEO Strategist? What about Content Strategist? or Offering Manager? I'm guessing they often decide what goes into a lead space.

**Comment by jeffchew** [comment]
_On May 15, Wonil-Suh1 commented:_
Regarding the first sentence, I agree on what's being proposed, but also agree with Lara on refining it a bit to include a content strategist, who is supposed to consider SEO. How about something like this:
**The lead space title should be appropriate for search engines. Work with an SEO or content strategist.**

**Comment by jeffchew** [comment]
_On May 15, chsanche commented:_
Agreed with both of you and that's exactly why I raised the concerns and we will talk about this in the Weekly Huddle.

**Comment by jeffchew** [comment]
_On Jun 25, chsanche commented:_
We will not update the current Lead Space page. The recommended change will be implemented in the new Gatsby website (#1124). This task issue will be closed.
