### ISSUE TITLE
Update Getting Started/Overview page content update for April release

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#2087]
> As an IBM.com Library adopter, 

> I need to see the latest information about the adoption routes and adoption resources (adopter starter kit)

> so that I know how to adapt properly and use the correct resource.

#### Additional information

Since we are open the website content to all IBMers, we need to take a look at the Getting Started/Overview page content and make the proper update.

#### Tasks

- [ ] The First audit is done by the leadership team (Linda, Wonil, and Jeff)
- [ ] Meet with Jenny to align on the changes/to-dos
- [ ] Create updates content for the live website update

#### Acceptance criteria
- [ ] Content is updated on the live website before April 24th.

**Comment by JennySanchez** [comment]
@wonilsuhibm Task issue created as discussed.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/ibm-dotcom-library-website #396](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/396) via [**ZenHub**](https://www.zenhub.com/)
