### ISSUE TITLE
Potential pattern previewer component

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#211]
_Wonil-Suh1 created the following on Apr 11:_  

 ### User story
As a maker I need a way to preview a pattern, understand the grids, get specs, and grab code so that I can use it the right way.

### Notes
(Modify as needed)

- Anything task detail you can share?
- Any resource links or documents do you have?
- Any specific time period this task should be completed?
- Does this task relate to any other task issues?
- Does this affect anyone else?

### Acceptance criteria
(Modify as needed)

- [ ] Design approved
- [ ] Code approved
- [ ] Sprint demoed
- [ ] OM accepted
- [ ] Guideline published
- [ ] Content published

###  Tasks
(Modify as needed)

**For Content:**
- [ ] Project kick off (at least: dev, designer, and content creator)
- [ ] Create content draft
- [ ] Review draft with key users (get feedback)
- [ ] Work on content revision
- [ ] Finalize content
- [ ] Have final content aproved

**For Design:**
- [ ] Project kick off (at least: dev and designer)
- [ ] Work on wireframe/Ideation
- [ ] Create Initital design
- [ ] Review deisng with team memebers (get feedback)
- [ ] Work on design revision
- [ ] Finalize design
- [ ] Have final design aproved

**For Code:**
- [ ] Project kick off (at least: dev and designer)
- [ ] Write code
- [ ] Review code with team memebers (get feedback)
- [ ] Work on code revision
- [ ] Finalize Code
- [ ] Have final code review and designer QA
- [ ] Set up PR request
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/715_

**Comment by jeffchew** [comment]
_On Apr 11, Wonil-Suh1 commented:_
Creating this issue to capture this idea:
![layout-preview-component--1 0 0 copy 2](https://media.github.ibm.com/user/25726/files/10012080-61f2-11e9-8b21-accbfa1f38de)

An idea on layout preview component. The Sketch file is [here](https://ibm.box.com/s/y845neg9cnzt9j5ylyifc60ld7x45nd4)

Would be great to conduct a bit of research around what other needs this component could support.

**Comment by JennySanchez** [comment]
**The latest component switch (a.k.a. previewer) from the Anna (Carbon Team):**
![image (1)](https://user-images.githubusercontent.com/45213839/68437416-806b9100-0186-11ea-9a5d-1c295ef81171.png)
![image copy](https://user-images.githubusercontent.com/45213839/68437420-819cbe00-0186-11ea-97e4-946dacf57106.png)

**Comment by JennySanchez** [comment]
**Note:** Updated information and conversation with Vince, the dev lead on the demo window, can be viewed via [issue 122](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/122).
