### ISSUE TITLE
Define contribution process across dotcom

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#214]
_Lisa-Lurie created the following on Apr 24:_  

 # As a contributor of code, I need to clearly know the process of adding new code or fixing a bug so that my work can be prioritized and accepted

This part of the contribution guidelines is so crucial for contributors not on our team. This document should provide our contributors with clear expectations from our team, and step by step instructions of how they can go from zero to hero.

![image](https://media.github.ibm.com/user/19/files/d6fc1980-67b8-11e9-9cd9-e2cbc05b5ee6)

### Resources for reference
 - [GitHub Help: Setting guidelines for repository contributors](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors)

### Acceptance criteria
- [ ] `CONTRIBUTING.md` file exists for [v18](https://github.ibm.com/webstandards/v18) within `.github` folder.
- [ ] `CONTRIBUTING.md` file exists for [v18-starter-kit](https://github.ibm.com/webstandards/v18-starter-kit) within `.github` folder.
- [ ] `CONTRIBUTING.md` file exists for [v19a](https://github.ibm.com/webstandards/v19a) within `.github` folder.
- [ ] `CONTRIBUTING.md` file exists for [patterns](https://github.ibm.com/webstandards/patterns) within `.github` folder.
- [ ] `CONTRIBUTING.md` file exists for [digital-design](https://github.ibm.com/webstandards/digital-design) within `.github` folder.
- [ ] `CONTRIBUTING.md` file exists for [carbon-integration-poc](https://github.ibm.com/webstandards/carbon-integration-poc) within `.github` folder.
- [ ] `CONTRIBUTING.md` file exists for [northstar-external-website](https://github.ibm.com/webstandards/northstar-external-website) within `.github` folder.
- [x] `CONTRIBUTING.md` file exists for [IBM/carbon-addons-dotcom](https://github.com/IBM/carbon-addons-dotcom) within `.github` folder.
- [ ] [TBD: https://github.com/carbon-design-system/ibm-dotcom-library/issues/214] `CONTRIBUTING.md` file exists for [IBM/dotcom-services](https://github.com/IBM/dotcom-services) within `.github` folder.
- [ ] [TBD: https://github.com/carbon-design-system/ibm-dotcom-library/issues/214] `CONTRIBUTING.md` file exists for [IBM/dotcom-bundles](https://github.com/IBM/dotcom-website) within `.github` folder.
- [ ] [TBD: https://github.com/carbon-design-system/ibm-dotcom-library/issues/214] `CONTRIBUTING.md` file exists for [IBM/dotcom-website](https://github.com/IBM/dotcom-website) within `.github` folder.
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/745_

**Comment by jeffchew** [comment]
_On Apr 24, james-dow commented:_
~@Lisa-Lurie is this issue different from #472?~ Talked to @Lisa-Lurie via Slack, and she differentiated them by saying this lives in the codebase, and #472 lives on the website itself. I'll update the tickets to try and clearly communicate this.

**Comment by jeffchew** [comment]
_On Apr 26, james-dow commented:_
Carbon gave us a great [CONTRIBUTION.md](https://github.com/IBM/carbon-addons-dotcom/blob/master/.github/CONTRIBUTING.md) file to be used on [carbon-addons-dotcom](https://github.com/IBM/carbon-addons-dotcom/). I doubt we can just copy and paste across the board, but it can serve as a good starting point and outline.

**Comment by RobertaJHahn** [comment]
Already created.  Closing
