### ISSUE TITLE
Add LICENSE to repos across dotcom

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#217]
_james-dow created the following on Apr 26:_  

 # As a contributor I sometimes need to understand what license is used so I can confidently decide whether I can use your project or not

Including a detectable license in our repository, people who visit your repository will see it at the top of the repository page. This is an absolute must with our public repos like [IBM/carbon-addons-dotcom](https://github.com/IBM/carbon-addons-dotcom), but for consistencies sake and communication purposes it might be a good idea to add to our projects across the board. This is important and potentially has legal implications.

Carbon, and our add-on is using `Apache License 2.0`

<img src="https://zenhub.ibm.com/images/5633c823f8b9062565e109ea/89dfe5c7-9675-4043-be7d-965b964f1f0a" width="300px" />

### Resources for reference
 - [GitHub Help: Adding a license to a repository](https://help.github.com/en/articles/adding-a-license-to-a-repository)
- [GitHub Help: Licensing a repository](https://help.github.com/en/articles/licensing-a-repository)

### Acceptance criteria
- [ ] `LICENSE.md` file exists for [v18](https://github.ibm.com/webstandards/v18) within `.github` folder.
- [ ] `LICENSE.md` file exists for [v18-starter-kit](https://github.ibm.com/webstandards/v18-starter-kit) within `.github` folder.
- [ ] `LICENSE.md` file exists for [v19a](https://github.ibm.com/webstandards/v19a) within `.github` folder.
- [ ] `LICENSE.md` file exists for [patterns](https://github.ibm.com/webstandards/patterns) within `.github` folder.
- [ ] `LICENSE.md` file exists for [digital-design](https://github.ibm.com/webstandards/digital-design) within `.github` folder.
- [ ] `LICENSE.md` file exists for [carbon-integration-poc](https://github.ibm.com/webstandards/carbon-integration-poc) within `.github` folder.
- [ ] `LICENSE.md` file exists for [northstar-external-website](https://github.ibm.com/webstandards/northstar-external-website) within `.github` folder.
- [x] `LICENSE.md` file exists for [IBM/carbon-addons-dotcom](https://github.com/IBM/carbon-addons-dotcom) within `.github` folder.
- [ ] [TBD: https://github.com/carbon-design-system/ibm-dotcom-library/issues/217] `LICENSE.md` file exists for [IBM/dotcom-services](https://github.com/IBM/dotcom-services) within `.github` folder.
- [ ] [TBD: https://github.com/carbon-design-system/ibm-dotcom-library/issues/217] `LICENSE.md` file exists for [IBM/dotcom-bundles](https://github.com/IBM/dotcom-website) within `.github` folder.
- [ ] [TBD: https://github.com/carbon-design-system/ibm-dotcom-library/issues/217] `LICENSE.md` file exists for [IBM/dotcom-website](https://github.com/IBM/dotcom-website) within `.github` folder. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/752_

**Comment by jeffchew** [comment]
_On Apr 26, vladislav-saling commented:_
@james-dow Do we need to run a license scan for vendor code? (e.g. with v18).

**Comment by jeffchew** [comment]
_On Apr 26, james-dow commented:_
Not sure, what do you mean by vendor code?

**Comment by jeffchew** [comment]
_On Apr 26, vladislav-saling commented:_
Select2, greensock etc. I spoke about these things with dev from knowledge center some time ago and he mentioned, that when they generate/make/create their licence it has to be aligned with licences or libraries, that their project is using (I think it was something along the lines, that you need to make sure that your own license doesn't contradicts license on vendor code). I am currently trying to confirm that. 

However, this is only about v18 as far as I can tell.

**Comment by RobertaJHahn** [comment]
Obsolete.
