### ISSUE TITLE
List CODEOWNERS, role, and responsibilities

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#218]
_james-dow created the following on Apr 26:_  

 # As a collaborator I need to know who I can request to review my pull request so my work doesn't get lost in the noise

Adding a CODEOWNERS file to our repositories can do two things for us. One it'll give a clear place where our contributors can see who is responsible for what. Second it automatically assigns the correct person when that section of the repository is touched, so they are made aware and can review.

### Resources for reference
 - [GitHub Help: About code owners](https://help.github.com/en/articles/about-code-owners)

### Acceptance criteria
- [ ] `CODEOWNERS.md` file exists for [v18](https://github.ibm.com/webstandards/v18) within `.github` folder.
- [ ] `CODEOWNERS.md` file exists for [v18-starter-kit](https://github.ibm.com/webstandards/v18-starter-kit) within `.github` folder.
- [ ] `CODEOWNERS.md` file exists for [v19a](https://github.ibm.com/webstandards/v19a) within `.github` folder.
- [ ] `CODEOWNERS.md` file exists for [patterns](https://github.ibm.com/webstandards/patterns) within `.github` folder.
- [ ] `CODEOWNERS.md` file exists for [digital-design](https://github.ibm.com/webstandards/digital-design) within `.github` folder.
- [ ] `CODEOWNERS.md` file exists for [carbon-integration-poc](https://github.ibm.com/webstandards/carbon-integration-poc) within `.github` folder.
- [ ] `CODEOWNERS.md` file exists for [northstar-external-website](https://github.ibm.com/webstandards/northstar-external-website) within `.github` folder.
- [ ] `CODEOWNERS.md` file exists for [IBM/carbon-addons-dotcom](https://github.com/IBM/carbon-addons-dotcom) within `.github` folder.
- [ ] [TBD: https://github.com/carbon-design-system/ibm-dotcom-library/issues/218] `CODEOWNERS.md` file exists for [IBM/dotcom-services](https://github.com/IBM/dotcom-services) within `.github` folder.
- [ ] [TBD: https://github.com/carbon-design-system/ibm-dotcom-library/issues/218] `CODEOWNERS.md` file exists for [IBM/dotcom-bundles](https://github.com/IBM/dotcom-website) within `.github` folder.
- [ ] [TBD: https://github.com/carbon-design-system/ibm-dotcom-library/issues/218] `CODEOWNERS.md` file exists for [IBM/dotcom-website](https://github.com/IBM/dotcom-website) within `.github` folder. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/755_
