### ISSUE TITLE
Tech Assessment with 2019 DDS adopters

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#223]
_Lisa-Lurie created the following on May 21:_  

 Meetings with the individual DGC Teams, to understand their current environments, tech stacks, roadmap, etc. Also to speak about NPM adoption.

## Acceptance Criteria
- [x] The architect has met with all of the adopter Technical Leads
- [x] The technical details needed to design the Digital Design System has been documented for each adopter
- [x] Technical status and gaps have also been documented for each adopter, to be used and input to build the IBM DDS roadmap 

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/849_

**Comment by RobertaJHahn** [comment]
Meetings have been conducted with all DGC adopters.  Closing.
