### ISSUE TITLE
IBM Digital Design Squad Tools and processes

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#237]
_hahnrob created the following on May 28:_  

 As an IBM Digital Design Squad team member, I need to be aware of the standard tools and processes used by the team so that I can create and share my work in a centralized way.

This is an ongoing epic used to link the work performed to organize the squad work.

#### Additional information
Tools and processes for the following work:
 - Design
 - Audit and analysis
 - Diagramming
 - Road mapping
 - Agile / Project management
 - Process documentation
 - Code
 - On-boarding documentation

#### Acceptance criteria
 - [ ] Documentation of the standard tools to be used for each work category
 - [ ] Audit of existing tools used by the team
 - [ ] Audit of the available tools
 - [ ] Tools must comply with the IBM security standards
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/897_

**Comment by jeffchew** [comment]
@RobertaJHahn this seems old. Think we can close this epic? I think #510 can be a standalone issue.

**Comment by RobertaJHahn** [comment]
Removed the issue 510 link to this epic.  Closing
