### ISSUE TITLE
Design assessment with 2019 DDS adopters

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#241]
_hahnrob created the following on Jun 05:_  

 Meetings with the individual DGC Teams, to understand their current design system

## Acceptance Criteria
- [x] The IBM DDS team has met with all of the adopter Design Leads
- [x] The design details have been documented for each adopter
- [x] Design status and gaps have also been documented for each adopter, to be used and input to build the IBM DDS roadmap  

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/949_

**Comment by RobertaJHahn** [comment]
Meetings have been conducted with all DGC adopters.  Closing
