### ISSUE TITLE
Update Content Group Component (Learn template enhancement)

### ISSUE THREAD

**Issue by kathysaraf** [carbon-design-system/ibm-dotcom-library#2472]
#### User Story
> As a `[user role below]`: ibm.com developer 

> I need to: provide an optional copy field

> so that I can: meet learn template enhancement requirements

#### Additional information
- Target to finish the functional specs is Friday, May 29.
- Design Box folders
-Content group with pictograms - https://ibm.ent.box.com/folder/94758548768
-Content group with cards - https://ibm.ent.box.com/folder/94755591200
-Content group simple - https://ibm.ent.box.com/folder/94758560782
- Optional copy field needs to be added to Content Group Simple, Content Group with pictograms, and Content Group with Cards (see attached screenshots)![ content group simple copy.png](https://images.zenhubusercontent.com/5e865397f55e02e7e862187b/0f535785-cb81-4222-a89d-360516cb7ebd)
![Content group with cards.png](https://images.zenhubusercontent.com/5e865397f55e02e7e862187b/56baf6ff-5ae4-4060-b0cd-8e0edbfe5e76)
![content group with pictograms.png](https://images.zenhubusercontent.com/5e865397f55e02e7e862187b/6cc292bf-5169-43ff-945f-b94222a14c70)
 - functional specs for content group simple: https://ibm.ent.box.com/folder/94758560782
- content group with pictograms: https://ibm.ent.box.com/folder/94758548768
- content group with cards: https://ibm.ent.box.com/folder/94755591200 
- TBD

#### Acceptance criteria
 - [x] Update the existing functional specs 
 - [x] notify dev when visual and func specs are complete
 - [x] create additional stories as needed

**Comment by kathysaraf** [comment]
Functional specs are here and updated - ready for review monday. @RobertaJHahn @jeffchew 

Content Group spec: https://ibm.ent.box.com/folder/99478674482  Latest version updated to include copy
Content Group with Pictograms: https://ibm.ent.box.com/folder/94758548768 latest version here with old one archived.
Content Group with Cards: https://ibm.ent.box.com/folder/94755591200 
Content Group Simple: https://ibm.ent.box.com/folder/94758560782

**Comment by RobertaJHahn** [comment]
Release v1.8.0 is finished.  All linked issues are closed.  Closing this epic.
