### ISSUE TITLE
Update Markdown Utility (Learn Template enhancement)

### ISSUE THREAD

**Issue by kathysaraf** [carbon-design-system/ibm-dotcom-library#2473]
#### User Story

> As an ibm.com developer 

> I need to update Markdown Utility 

> so that I can provide links and lists via markdown

#### Additional information

We are adding links and lists
- Target to finish the functional specs is Friday, May 29.
 - existing functional spec - https://ibm.ent.box.com/file/604090824435
- https://www.carbondesignsystem.com/components/link/usage
- https://www.carbondesignsystem.com/components/list/usage
- Designs provided by Reboot
-visual specs for lists - https://ibm.ent.box.com/folder/114067201736

![markdown utility link update.png](https://images.zenhubusercontent.com/5e865397f55e02e7e862187b/7eb28fdf-9113-431e-891f-1851559ac233)

![image.png](https://images.zenhubusercontent.com/5e865397f55e02e7e862187b/32f95cc5-97a4-46c7-9d84-d04a3403b623)

#### Acceptance criteria
 - [ ] Update existing functional specs 
 - [ ] notify dev when visual and func specs are complete
 - [ ] create additional stories as needed

**Comment by shixiedesign** [comment]
Hi @ellenchoi1 here's the visual spec for `List` for Digital https://ibm.box.com/s/zsf9wimd4o20s14l137amb3583n1h4l3

**Comment by ellenchoi1** [comment]
markdownToHTML utility func specs v1.1 uploaded to box: https://ibm.box.com/s/tx52qupoc0hkb00dnkwxcsn8agcxfdak

Refer to change log for details of updates.

Note, I made an assumption that 'on click', the links will load in the same tab since the Carbon component documentation does not refer to supporting the option to open in a new tab - https://www.carbondesignsystem.com/components/link/style

cc: @RobertaJHahn @kennylam
