### ISSUE TITLE
Hills 2020: co-ordinate and support prep work

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#2540]
DDS team is planning to write Hills. In order to successfully create Hills together, we need research and alignment around core findings and artifacts.

### Tasks
- [x] Lara to confirm facilitator(s) 
- [ ] Lara to co-ordinate schedules and agenda between DDS leads and facilitators
- [ ] Lara to collect and share links and artifacts with facilitators in advance of the workshop
- [ ] Lara to provide a list of all attendees (name, role, email) to facilitators 

### Acceptance criteria
- [ ] DDS leads agree to agenda 
- [ ] DDS team members are able to attend
- [ ] Facilitators have adequate support to plan for the workshop
