### ISSUE TITLE
Update Quote with 3rd line source

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#2584]
#### Additional information
 - [Lila's comment](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2116#issuecomment-629429012)
 - [Quote directory](https://ibm.ent.box.com/folder/110531199928)

When we originally spec'd this out we must have missed the third line in the source. After a conversation with Jeff we decided to add an extra prop for this. Need to reflect this change in the functional specs, and create a dev ticket to update this as a feature request.

See highlighted in visual below.

<img src="https://user-images.githubusercontent.com/3793636/83266572-a1c6b580-a188-11ea-9300-731ed4240d30.png" width="200px" />

#### Acceptance criteria
 - [ ] Create additional dev stories as needed.
 - [ ] Functional specs udpated
 - [ ] Quote takes in 2 lines of description not including the name/heading.

**Comment by photodow** [comment]
Here are the updated functional specs...
https://ibm.box.com/s/wcjfuhhzfr3ef219bjvhhezic767rzn7

Here is the dev issue I created...
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2685

**Comment by RobertaJHahn** [comment]
Functional specs reviewed with dev's and sized in the engineering meeting on Monday, June 9, 2020
