### ISSUE TITLE
Design left navigation

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#263]
_Wonil-Suh1 created the following on Jun 23:_  

 

As a IBM dot com user, I need a way to navigate through 3rd level contents (page level).

Scott's studies: [#526](https://github.ibm.com/webstandards/digital-design/issues/526)

#### Tasks
- [ ] Meet with Commerce tribe (Charlie Douglas) to discuss timeline and collaboration model

#### Acceptance criteria
- [ ] New design have been created
- [ ] New design has been accepted by the Commerce tribe leadership
- [ ] Shared on Wake for feedback
- [ ] Shared with IDL for feedback
- [ ] Reviewed and approved by dev team
- [ ] Approved by DGC design leadership (Wonil Suh, Charlie Douglas, & Elliott Trice)

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1096_

**Comment by wonilsuhibm** [comment]
Let's keep this alive as a way to capture the support we provide to the Commerce team.

**Comment by ljcarot** [comment]
This is okay to close. Commerce experience has designed their left nav.
