### ISSUE TITLE
Design Chat

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#264]
_Wonil-Suh1 created the following on Jun 23:_  

 

As an IBM dot com user, I need a way to talk to IBM representatives to have my questions answered and resolve my issues.

This is mainly designed by UMX team.

#### Additional Information
- The priority is documented in the component [Airtable](https://airtable.com/tblYos5iDYwTP6MCK/viw85GYbUVISjrXj9?blocks=hide)
 - Assigned priority:  #6

#### Tasks
- [ ] Meet with UMX team to discuss timeline and collaboration model
- [ ] Meet establish testing plans

#### Acceptance criteria
- [ ] New design have been created
- [ ] New design has been accepted by the UMX team leadership (Dave McDuff)
- [ ] Shared on Wake for feedback
- [ ] Shared with IDL for feedback
- [ ] Approved by DGC design leadership (Wonil Suh, Charlie Douglas, & Elliott Trice) 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1097_
