### ISSUE TITLE
Hills post-workshop support and next steps

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#2696]
We need to document the outcomes of the Hills workshop so that we can refine the work done and move forward as a team.

### Tasks

- [x] Connect with Emery and Abigail for advice and guidance on next steps
- [x] Save Mural outcomes
- [x] Document WIP Hills
- [ ] Document Social Contract
- [ ] Set up time with DDS Leads to review next steps

**Comment by larahanlon2** [comment]
**Hills continuation was scheduled for today, Thursday June 25. Due to conflicts we need to reschedule to July 9.**

Here is the proposed agenda:
- Review Mural board – 10 mins
- Assumptions/questions – 20mins
- Vote – 2mins
- Rewrite – 15mins
- Prioritization – 15mins

**Comment by larahanlon2** [comment]
Hills v2 refinement took place during squad huddle on July 9. Based on the feedback and discussions by the entire team, Lara, Jenny and Jacob continued the refinement and rewrite in [Mural](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1594301545409?sender=larahanlon9022&key=d470a59d-331c-41c0-a39b-ddd3cdfacce7).

Current leading Hill that needs further critique and validation from the team:

## By discovering and using IBM.com Library, designers and developers can apply Carbon to IBM.com pages with *limited hand holding from DSS team. 
***limited hand-holding: adopters can access and use the approved assistance, tools, and support systems.**

**Comment by larahanlon2** [comment]
Closing this issue as the next steps were determined. A new issue will be opened for the continuation of the refinement work.
