### ISSUE TITLE
Identify layout patterns based on journey system and page categories 

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#271]
_larahanlon created the following on Jun 27:_  

 

# As a maker of ibm.com pages, I need guidance and examples for best layout patterns so that my users can find and enjoy page content on ibm.com.

## Additional information
We want to identify, create and share layout designs and guidelines for different experiences across ibm.com. Content can be composited in many ways across a single user journey to support user intent. The layout of each page will change depending on the overall purpose of that page.

## Tasks
- [ ] Collect journey system map (5 E's) and content types
- [ ] Identify page categories based on Jill's list
- [ ] Update Airtable with layout pattern types

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1137_

**Comment by larahanlon2** [comment]
Closing this out because it's not our work anymore. It's for Web Simplification.
