### ISSUE TITLE
Pattern:  CTA section - remove the horizontal rule when no content items are given - Services template requirements

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2778]
This epic will contain a description of the overall scope, development instructions and links to all of the issues required to complete the work.

#### Additional Information
- Target end dates:
    - Functional specs - Friday, June 19.  
    - Development - Friday, June 26
    - Prod QA - Friday, July 3
- [Reboot Consulting Services designs](https://ibm.ent.box.com/file/679166003833)
- [Reboot Services pattern scope and pattern analysis Box Note](https://ibm.ent.box.com/notes/677586401007?s=j845wnqyyrxrfydjv7a392mz0iakkut5)
- [Designs and functional specs Box folder](https://ibm.ent.box.com/folder/109648616047)

#### Acceptance criteria
- [x] Functional specs are documented.  Summary and links are posted to this epic
- [x] Designs and functional specs are reviewed with the DDS developers for sizing and issue refinement
- [x] Additional stories are created, if needed, for any work to be done in future sprints.

**Comment by RobertaJHahn** [comment]
@photodow Here is the epic for the CTA section functional specs.

**Comment by photodow** [comment]
Updated functional specs to be more explicit in how the horizontal rule functions depending on how many items are below it.

https://ibm.ent.box.com/file/680498050634
