### ISSUE TITLE
Pattern:  Content block - with cards:  include an optional CTA

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#2792]
This epic will contain a description of the overall scope, development instructions and links to all of the issues required to complete the work.

#### Additional Information
- This work is currently scheduled as 'post MVP', but the development can begin as soon as the designs are available.
- Target end dates:
    - Functional specs -   
    - Development - 
    - Prod QA - 
- [Updated functional specs](https://ibm.ent.box.com/file/681042575001)

#### Acceptance criteria
- [x] Functional specs are documented.  Summary and links are posted to this epic
- [ ] Designs and functional specs are reviewed with the DDS developers for sizing and issue refinement
- [ ] Additional stories are created, if needed, for any work to be done in future sprints.

**Comment by photodow** [comment]
Updated functional specs with optional CTA.
https://ibm.ent.box.com/file/681042575001
