### ISSUE TITLE
Finalize pattern wireframes images with leads

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library#3218]
### Tasks
- [ ] Review the images with Wonil and Linda for feedback via issue: #488
- [ ] Make changes as needed.
- [ ] Finalize wireframes images. 

### Acceptance criteria
- [ ] Images are ready for publishing.
