### ISSUE TITLE
(Cuprske Website) Tile view implementation for the Components and Layout Patterns overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#3276]
#### Note
The finalized wireframe images for the tile view can be found (Coming soon by end of Sprint 20-15).

### Tasks

- [ ] Go over the task detail and kick off with Jenny
- [ ] Implement the tile set up on the Components and Layout Patterns overview page with code
- [ ] Share the preview link with Jenny for QA
- [ ] Merge PR for the tile view to go live on the Cupcake Website

### Acceptance criteria
- [ ] All Components and Layout Patterns are presented in the Tile view live on the cupcake website.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/ibm-dotcom-library-website #541](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/541) via [**ZenHub**](https://www.zenhub.com/)
