### ISSUE TITLE
Finalize componets wireframes images

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#3288]
### Tasks
- [ ] Review the images with Wonil and Linda for feedback
- [ ] Make changes as needed.
- [ ] Finalize wireframes images. 

### Acceptance criteria
- [ ] Images are ready for dev implementation.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/ibm-dotcom-library-website #544](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/544) via [**ZenHub**](https://www.zenhub.com/)
