### ISSUE TITLE
Create clickable prototype for locale selector test

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#364]
_larahanlon created the following on Aug 19:_  

 

### User Story
As an ibm.com user, I need a way to know when and why I am leaving my preferred language so that I can make a decision about my language of choice as I continue.

## Additional information
- Locale Selector designs were complete and approved in https://github.com/carbon-design-system/ibm-dotcom-library/issues/364 
- This issue captures the work required for the creation of a clickable prototype which will be used for the user test https://github.com/carbon-design-system/ibm-dotcom-library/issues/364 

## Tasks
- [x] Lara to create InVision prototype with latest designs

## Acceptance criteria
- [x] Scott reviews and accepts the prototype for test plan
- [x] Ben reviews and accepts the prototype for test plan

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1485_

**Comment by jeffchew** [comment]
_On Aug 19, larahanlon commented:_
InVision prototype can be found [here](https://ibm.invisionapp.com/share/26NZ77UF57S#/319222152_01-Ibm_UK-Home).

**Comment by jeffchew** [comment]
_On Aug 22, larahanlon commented:_
After review with Ben and Scott, need to:
- [x] Update the list view to allow for a fake scroll in InVision
- [ ] Translate flow to German
- [ ] If possible, ask a German-speaking colleague to review before testing

**Comment by jeffchew** [comment]
_On Aug 22, larahanlon commented:_
Just in from Mary. Will need to make this change to the designs and prototype.

> Hi, I have learned that on the country selector overlay, we need to use the term 'country/region' for political purposes as Taiwan is not a recognized country by China. 
>  
> So it should read 'Select your country or region'
>  
> This means that on the overlay that we have designated as the region selector, we need different wording. I recommend we use 'Select your geographic area' for the test. 
>  
> Let me know if you have questions - thanks
> Mary O'Donnell

**Comment by jeffchew** [comment]
_On Aug 26, larahanlon commented:_
@Benjamin-Hansen1 @james-dow @spbokma 
Hey, I updated the clickable prototype and translated to German: https://ibm.invisionapp.com/share/B6NZ7YTF42S#/319230812_01-Germany-Home

Included the fake scroll and new copy from Mary. Obviously this is not in English but please check this out and let me know if it works for you. I can share an English version soon. P.S unfortunately, I wasn't able to find someone to proof the translation yet!

**Comment by jeffchew** [comment]
_On Aug 27, larahanlon commented:_
@Benjamin-Hansen1 the English version is here (it's the one we walked through last week so it's not as updated as the German version above) https://ibm.invisionapp.com/share/26NZ77UF57S

**Comment by jeffchew** [comment]
_On Aug 28, larahanlon commented:_
@Benjamin-Hansen1 I updated the list of locations/languages: https://ibm.invisionapp.com/share/B6NZ7YTF42S

**Comment by jeffchew** [comment]
_On Aug 29, larahanlon commented:_
I was able to have not just 1 but 2 German IBM colleagues proof read this prototype! All edits are now made and the final prototype can be found here: https://ibm.invisionapp.com/share/B6NZ7YTF42S#/319230812_01-Germany-Home

**Comment by jeffchew** [comment]
_On Sep 03, larahanlon commented:_
This was updated and accepted for the user test, which Ben is now running. #1229 

Closing.
