### ISSUE TITLE
Finalize site map for DDS Cupcake site

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#370]
_chsanche created the following on Aug 26:_  

 ### User Story
As a member of the DDS team, I need a site map to guide my Cupcake website development work so that I can assure that any updates or new pages to the DDS site are within the site map plan.

### Deliverables
- [x] DDS Cupcake website v1.0 sitemap

### Acceptance Criteria
- [x] Validate the sitemap meeting adopter needs.
- [x] Sitemap reviewed and approved by stakeholders.
- [x] Sitemap shared in DDS team playback. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1518_

**Comment by jeffchew** [comment]
_On Sep 04, chsanche commented:_
**Task Update:**
- Collecting pain points from designers to inform updates needed.
- Navigation explorations alignment call scheduled by Jan for 09/09.

**Comment by jeffchew** [comment]
_On Sep 06, chsanche commented:_
Latest website sitemap with priority setting as 09-06 
Sketch work file saved in [BOX folder](https://ibm.box.com/s/6n9kwg0txzirvpc787n63hrneh01qxzq).


![screen shot 2019-09-09 at 2 47 45 pm](https://media.github.ibm.com/user/5181/files/dfd92c00-d310-11e9-803e-868ad90125fd)



![screen shot 2019-09-09 at 2 47 33 pm](https://media.github.ibm.com/user/5181/files/e798d080-d310-11e9-93f1-2b72a238dc59)

**Comment by jeffchew** [comment]
_On Sep 09, chsanche commented:_
@spbokma The sitemap is updated based on our discussion earlier today. As a reminder, it will be good to take a look at the adopter pain point document (#1370) to help us finalize the sitemap this sprint.

Please let me know if you have any other questions.

**Comment by jeffchew** [comment]
_On Sep 10, chsanche commented:_
@spbokma The final sitemap is updated based on our discussion earlier.
The [Sketch work file](https://ibm.box.com/s/6n9kwg0txzirvpc787n63hrneh01qxzq) in the BOX folder is updated as well.

![screen shot 2019-09-10 at 1 11 37 pm](https://media.github.ibm.com/user/5181/files/1166fb80-d3d4-11e9-9266-4a7b4afec380)

**Comment by jeffchew** [comment]
_On Sep 10, chsanche commented:_
@Wonil-Suh1 The list is created based on the stream lead's content list and validated with the adopter feedback. Please let Scott and I know if you have any questions after reviewing it. 

FYI - A work session is scheduled for you and me to get the page content creation priority ready next Tuesday.

**Comment by jeffchew** [comment]
_On Sep 10, Wonil-Suh1 commented:_
@chsanche @spbokma Thank you.

Added some comments and questions here:

![dds-cupcake-site--comments](https://media.github.ibm.com/user/25726/files/8e9b6c00-d3e6-11e9-871b-0f40418601fd)

**Comment by jeffchew** [comment]
_On Sep 10, chsanche commented:_
@Wonil-Suh1 

Q: Is the Overview page under "Get Started" category about the Digital Design System itself?
A: Yes, but not fully. It also provides other information that our adopters need to get started and the differences between the versions of the DDS website.


Q: Is Guideline the right category for "Frameworks"?
A: We have the "Frameworks/Packages" under guideline because it will include guidelines for React, Styles, Utilities, Services, etc for the coder.


Q: Should we have the "Journey system" on the sitemap?
A: For the Cupcake version, "Journey system" did not come up in the adopter feedback as to their immediate need nor on the list from the stream leads. So we are planning on including it to the Wedding Cake version of the website instead.

We can add it if there's an adopter immediate need, and If we add it, I'd recommend under the "Resources" category.


Q: Are we going to have the "Roadmap" somewhere?
A: The Roadmap will be addressed and linked from the Homepage. 


Q: Shouldn't we list the order of the elements follow what IDL has?
A: We go in alphabetical order and it's the same to Carbon. It's also easier for the adopters to find the elements. Pictogram and motion are scoped for the Wedding Cake website because it did not come up from the adopter feedback as to their immediate needs.


Q: Is the Expressive Themes page for addressing the type and color themes? 
A: Not really, we recognize designers need guidance around what the "Expressive theme" is and should be able to differentiate the usage between the "Productive/Carbon" and "Expressive/IBM.com" themes for now so we are planning on providing guidelines on when to use it and how to use it here. Scott started the conversation with the Carbon team around what "Theme/Themeing" is and what we should cover under this umbrella. My thought is we will add the new information as we go and as needed for the Cupcake website.


Q: Why "Local Selector" is not under the "Components" category but in both "Components" and "Patterns" categories?
A: We have the Local Selector as an individual component under the "Components" category and the "Patterns" category because they have different levels of information and focuses. If we need to consolidate the content, I agree we should have it under the Component category and have the pattern usage included there.

---

@spbokma Please feel free to add anything I might be missed.

**Comment by jeffchew** [comment]
_On Sep 11, spbokma commented:_
@chsanche All is correct. 

@Wonil-Suh1 Please let us know if you have more questions.

**Comment by jeffchew** [comment]
_On Sep 11, chsanche commented:_
@Wonil-Suh1 @spbokma 

**Sitemap updated** -  "Local Selector" is a component and will live under the "Components" category.
Work file updated as well and can be found [here](https://ibm.box.com/s/6n9kwg0txzirvpc787n63hrneh01qxzq).

<img width="1200" alt="dds-cupcake-sitemap-v1 0" src="https://media.github.ibm.com/user/5181/files/d7aff680-d4a0-11e9-941c-881ea9cf882b">

**Comment by jeffchew** [comment]
_On Sep 12, Wonil-Suh1 commented:_
Thank you @chsanche and @spbokma !

Q: Is the Expressive Themes page for addressing the type and color themes?
A: Not really, we recognize designers need guidance around what the "Expressive theme" is and should be able to differentiate the usage between the "Productive/Carbon" and "Expressive/IBM.com" themes for now so we are planning on providing guidelines on when to use it and how to use it here. Scott started the conversation with the Carbon team around what "Theme/Themeing" is and what we should cover under this umbrella. My thought is we will add the new information as we go and as needed for the Cupcake website.
Q2: I wonder if the name of the page, "Expressive theme" is correct since it will be covering both expressive and productive themes.

**Comment by jeffchew** [comment]
_On Sep 12, chsanche commented:_
If we are covering both, maybe we should leave it as "Theme" or "Theming". 
@spbokma What do you think?

**Comment by jeffchew** [comment]
_On Sep 17, chsanche commented:_
- Based on the discussion we had today, we will use "Themes".
- We also added Number picker and Tooltips to the Components category based on the Modern Commerce Squad need.
- Sitemap and work file updated.

![dds-cupcake-sitemap-v1 0](https://media.github.ibm.com/user/5181/files/7b0d7080-e3a8-11e9-9285-8ee8888849c7)

**Comment by jeffchew** [comment]
_On Sep 18, hahnrob commented:_
Presented in Sept 18 sprint review meeting.  Closing.
