### ISSUE TITLE
Design kit: add low contrast notifications and action variant

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#377]
_Olivia-Flory created the following on Aug 29:_  

 ### Add the low contrast notifications to the design kit

**Notes**
Carbon recently added the low contrast variants of the notification component into the system
![Screen Shot 2019-08-29 at 4.29.50 PM.png](https://zenhub.ibm.com/images/5bc1083e9c7a4b4b3d71ae3e/503fa778-9366-4f1c-ad0d-7a7ca1ded2fc)

They also added an 'action' variant to all notifications

**Tasks**
- [x] add low contrast variants
- [x] test low contrast variants
- [x] add action variants
- [x] test action variants
- [x] restructure symbols to reflect updated groupings

**Acceptance criteria**
- [x] all notification variants added to the kit
- [x] symbols reflect the same structure as Carbon kit
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1548_

**Comment by jeffchew** [comment]
_On Sep 30, Olivia-Flory commented:_
Check with Carbon why the pieces are not linked in the main symbol
