### ISSUE TITLE
Cupcake website page creation - Components/Modal page

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#423]
_chsanche created the following on Sep 10:_  

 

#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the components, patterns, etc

> so that I can: do my day to day work without confusion.

#### Additional information
- Cupcake website page development priority can be viewed via https://github.com/carbon-design-system/ibm-dotcom-library/issues/423.
- Modal page on v19a website can be viewed [here](https://www.ibm.com/standards/web/components/modal/).
- Modal page on the current Carbon Design website can be viewed [here](https://www.carbondesignsystem.com/components/modal/usage)

#### Task
- Collaborate with Olivia for the content creation.

#### Acceptance criteria
- [x] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [x] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the dev. issue for coding as the next step.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1668_

**Comment by jeffchew** [comment]
_On Sep 10, chsanche commented:_
@hahnrob Story point will be adjusted once the #1664 is completed - FYI.

**Comment by jeffchew** [comment]
_On Sep 23, chsanche commented:_
@Olivia-Flory @Wonil-Suh1 

The content is crafted based on the content template Jillian created and approved for the Carbon Team. Please take a look of the Modal page content and let me know if there are any changes we need to make.

Reminder: For the Cupcake website, we need to have the page content as lean as possible. We can add other additional information or advanced features later but for now, let's ask IBM.com designers to get started and use the Modal from the Design Kit. For the Wedding Cake website, we will consider adding a Live demo, Theming, and Specs to this page, because Carbon Team is in a discussion about that right now.

---

![modal](https://media.github.ibm.com/user/5181/files/0791bf00-ddfc-11e9-8019-898c231c5007)

**Comment by jeffchew** [comment]
_On Sep 23, Olivia-Flory commented:_
@chsanche this is super exciting, thank you for sharing! Overall looking awesome, below are a few things I noticed: 

1. In the input modal example, the text input field color should be set to `field-02` so it appears as white on the gray background for accessibility. This is how you can change it in the overrides panel
<img width="841" alt="screen shot 2019-09-23 at 1 32 43 pm" src="https://media.github.ibm.com/user/192199/files/37928f80-de07-11e9-8a63-04d22172d4e6">

2. Carbon's coded example of the input modal shows the input field spanning 75% the width of the modal however, the written guidance under "Body" says form inputs can span the full width. Maybe we can get clarification from the Carbon team which is correct. 

3. In the footer section, I think "button" at the end of the first sentence should be plural. 
"The footer area of a modal typically contains either one or two buttons."


For the cupcake are we showing static examples of each component or are the white fields interactive like in the Code pages on Carbon's website?

**Comment by jeffchew** [comment]
_On Sep 23, chsanche commented:_
@Olivia-Flory 

Good catch and the image is updated now. For the input modal width, I confirmed with Anna. The input field can fill the full width, but the length of the text should always be at 75%.





![modal](https://media.github.ibm.com/user/5181/files/3458cd00-de22-11e9-854b-4f8f9704d31c)

**Comment by jeffchew** [comment]
_On Sep 26, chsanche commented:_
@Wonil-Suh1 Follow up on the Modal page review. 

I shifted the content order for it to match the Carbon component template. Let me know if there are any edits needed before we close this issue tomorrow.

![modal latest](https://media.github.ibm.com/user/5181/files/b7199c00-e05d-11e9-918e-220ee4320dc8)

**Comment by jeffchew** [comment]
_On Sep 30, linda-carotenuto commented:_
This is looking great y'all.
