### ISSUE TITLE
Pattern design kit architecture & strategy

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#455]
_Wonil-Suh1 created the following on Sep 17:_  

 ### User story
As a designer of IBM.com experiences, I need a standardized design kit with all available patterns so that I can design correctly and quickly, while the library does not slow down my Sketch app.

### Notes
We need to come up with how to build pattern design kit based on learnings from the component design kits, and plan a roadmap.

We have a few questions that we need to answer in this work:
- How many library files do we need to break this into, in order to maintain Sketch app performance?
- What is the best organization of patterns, per touch point? per purpose, per color theme?
- How do we handle patterns that are used in multiple templates?
- Can we enforce specs such as char count?
- How do we handle char count variations and the number of text lines - one line, two lines, three lines, etc?
- How do we handle pattern variations, such as centered lead space and default lead space?
   - Is default lead space the right name?

### Acceptance criteria
- [ ] Library file organization structure has been created
- [ ] Symbol organization structure has been created
- [ ] Where library files will be published has been determined
- [ ] At least one library file is created with at least one simple pattern (simple benefits pattern suggested) and tested through the determined publishing location

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1721_

**Comment by jeffchew** [comment]
_On Oct 01, Wonil-Suh1 commented:_
Suggested next step is a discovery build of two patterns - one of the lead space patterns and the simple benefits pattern.

**Comment by oliviaflory** [comment]
@wonilsuhibm is this epic stale?

**Comment by wonilsuhibm** [comment]
@oliviaflory No it's not. not yet.

**Comment by RobertaJHahn** [comment]
This is an obsolete epic.  A pattern design kit will not be created.  Closing
