### ISSUE TITLE
Cupcake website page creation - Resources category

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#484]
_chsanche created the following on Sep 24:_  

 

#### User Story

> As an IBM.com page creator

> I need to: know where to find resources

> so that I can: do my day to day work efficiently.

#### Additional information
- Cupcake website page development priority can be viewed via https://github.com/carbon-design-system/ibm-dotcom-library/issues/484.
- The Resources page on the Carbon Design website can be viewed [here](https://www.carbondesignsystem.com/resources)
- We are going to combine all the resources into one page for the Cupcake version.
![Screen Shot 2019-09-24 at 1.33.25 PM.png](https://zenhub.ibm.com/images/569d5727c35226c2f582fbc9/a2fc5ae7-3e4c-4061-ba5b-e7769e9cfce1)

#### Task
- Collaborate with Wonil and Jeff for the content creation.

#### Acceptance criteria
- [x] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the dev. issue for coding as the next step.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1759_

**Comment by jeffchew** [comment]
_On Oct 01, chsanche commented:_
@Jeff-Chew @Benjamin-Hansen1 @Wonil-Suh1 

Please take a look at the content for the Resources page below and let me know if anything is missed.

![resources](https://media.github.ibm.com/user/5181/files/adbd7480-e44d-11e9-9045-bd076f76f233)

**Comment by jeffchew** [comment]
_On Oct 10, Jeff-Chew commented:_
We will have storybook for patterns, as well as JSDoc for services and utilities. 

Is it confusing to add the v19 repo here? I think that should stay with the old standards site.

**Comment by jeffchew** [comment]
_On Oct 10, linda-carotenuto commented:_
I agree...don't need V19 repo here.

**Comment by jeffchew** [comment]
_On Oct 11, chsanche commented:_
@linda-carotenuto @Wonil-Suh1 

Resources Page update completed.
- v19a Github repo card deleted.
- IBM.com Pattern React Storybook (experimental) card added.
- IBM Research card added.
- Slack logo SVG on the cards updated.

---

![resources - v2](https://media.github.ibm.com/user/5181/files/a86edf80-ec2e-11e9-8937-0fd55c193ccd)

**Comment by JennySanchez** [comment]
Added the IBM style guideline card (see request via [issue 746](https://github.ibm.com/webstandards/digital-design/issues/746) for detail) to the Resources page.

**Final design:**
![Resources - v2.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/3e9f3777-7396-4f12-8849-2f10ce08b757)
