### ISSUE TITLE
[Design kit]: add masthead

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#489]
_Olivia-Flory created the following on Sep 26:_  

 ### User story
As a designer, I need access to visual design symbols of the new masthead, so I can align my designs to the new standard.

### Notes
- Designers need to use the new masthead in their designs so they don't confuse the developers with the northstar masthead
- we need to include the masthead in a design kit 

#### Outstanding questions
- should it be included in the Expressive design kit?
- should the masthead be in a IBM.com library design kit?
- list of customizable pieces

### Tasks
- [ ] identify which pieces of the masthead are customizable
- [ ] figure out symbol structure
- [ ] cover all breakpoints
- [ ] cover all variations
- [ ] add symbols to design kit

### Acceptance criteria
- [ ] Symbols match design and code specifications
- [ ] Design reviewed by Wonil / Lara
- [ ] Design approved Wonil / Lara 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1777_

**Comment by oliviaflory** [comment]
**Notes**
- Look at story book for final specs
- Teams should not be allowed to turn off search *or* MyIBM links
- will follow Carbon's naming convention for items to start
- Maximum of 7 menu links within the L0 
- Maximum character count of 55
- Only allowing hyphen and ampersand for special characters
