### ISSUE TITLE
[Design kit]: add footer

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#490]
_Olivia-Flory created the following on Sep 26:_  

 ### User story
As a designer, I need access to visual design symbols of the new footer, so I can align my designs to the new standard.

### Notes
- Designers need to use the new footer in their designs so they don't confuse the developers with the northstar footer
- we need to include the footer in a design kit 

#### Outstanding questions
- should it be included in the Expressive design kit?
- should the footer be in a IBM.com library design kit?
- is any of it customizable?

### Tasks
- [x] identify which pieces of the footer are customizable
- [x] figure out symbol structure
- [x] cover all breakpoints
- [x] cover all variations
- [x] add symbols to design kit

### Acceptance criteria
- [x] Symbols match design and code specifications
- [ ] Design reviewed by Wonil 
- [ ] Design approved Wonil  

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1778_

**Comment by oliviaflory** [comment]
@wonilsuhibm I have all the footer versions in this file: https://ibm.ent.box.com/folder/90951802351

Things we need to discuss: 
- size of logo at different breakpoints
- logo margin at different breakpoints 
- locale selector
   - how it's placed on the columns
   - should we include it or hide it until the locale selector is ready in code?

**Comment by wonilsuhibm** [comment]
@oliviaflory was our conversation the other day enough to answer your questions?

The locale selector should be hidden until it becomes available.
