### ISSUE TITLE
Cupcake website page creation - Help/Overview page

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library#498]
_chsanche created the following on Oct 02:_  

 

#### User Story

> As an IBM.com page creator

> I need to: know where to find help resources

> so that I can: do my day to day work efficiently.

#### Additional information
- Cupcake website page development priority can be viewed via https://github.com/carbon-design-system/ibm-dotcom-library/issues/498.
- The Help page on the Carbon Design website can be viewed [here](https://www.carbondesignsystem.com/help/support)
- The current v19a website does not have the "Help" section. The Support link on the v19a website footer can be viewed [here](https://www.ibm.com/support/home/?lnk=fcw)

#### Task
- Collaborate with Wonil for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the dev. issue for coding as the next step.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1796_

**Comment by JennySanchez** [comment]
There are a few things I need to confirm with the stream leads and Wonil to finalize this page content. I signed up for the Wednesday team huddle for discussion and will make updates based on the outcome.

---

**First draft content and design below:**
![Helpl.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/1af3b77c-d14f-4d4a-86fd-f28e61cb5878)

**Comment by JennySanchez** [comment]
**The Help page is updated based on the team Huddle discussion:**

![Help-v2.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/67142f6f-2538-477d-9d57-e33c62843210)

---

@jeffchew Please provide the list and link URL for the "Code issues" section (see below for reference) as discussed. 

![Screen Shot 2019-10-17 at 2.24.57 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/569ffc56-0c6c-4f7a-aa01-437ff42a9386)

**Comment by RobertaJHahn** [comment]
Here is the link for users to submit website issues:
https://github.com/carbon-design-system/carbon-for-ibm-website/issues/new/choose

Here is the link for users to submit design kit issues:
https://github.com/carbon-design-system/carbon-for-ibm-design-kit/issues/new

**Comment by RobertaJHahn** [comment]
the list of code issues is:
Bug
React (components)
React (patterns)
Vanilla (components)
Vanilla (patterns)
Vanilla is coming soon.

**Comment by JennySanchez** [comment]
Help page updated based on the work session today with Robera and Jeff.

![Help - v3.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/c6f8d850-1253-4361-ab3c-3d668c0d34c3)

---


@jeffchew Can you confirm the links are listed correctly? Thank you.

**Design Issues:**
- Accessibility
https://github.com/carbon-design-system/ibm-dotcom-library/issues/new/choose
- Components
https://github.com/carbon-design-system/ibm-dotcom-library/issues/new/choose
- Design kit
https://github.com/carbon-design-system/carbon-for-ibm-design-kit/issues/new
- Icon usage
https://github.com/carbon-design-system/ibm-dotcom-library/issues/new/choose
- Icon requests
https://github.com/carbon-design-system/carbon-icons/issues/new
- Patterns
https://github.com/carbon-design-system/ibm-dotcom-library/issues/new/choose
- Website
https://github.com/carbon-design-system/carbon-for-ibm-website/issues/new/choose

**Code Issues:**
- Bug
https://github.com/carbon-design-system/ibm-dotcom-library/issues/new?labels=bug&template=bug_report.md
- React components
https://github.com/carbon-design-system/ibm-dotcom-library/issues/new/choose
- React patterns
https://github.com/carbon-design-system/ibm-dotcom-library/issues/new/choose
- Vanilla components
(coming soon)
- Vanilla patterns
(coming soon)

**Comment by JennySanchez** [comment]
☝️☝️☝️ **Note:** We need to update the email address once #539 is completed.

**Comment by RobertaJHahn** [comment]
Presented in the Oct 28 Sprint Review meeting.  Closing.
