### ISSUE TITLE
Cupcake website page creation - Guidelines/Layout page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library#543]
#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the layout

> so that I can: do my day to day work without confusion.

#### Additional information
- Cupcake website page development priority can be viewed via #1664.
- Layout guideline page on v19a website can be viewed [here](https://www.ibm.com/standards/web/design-guidelines/layout.html).

#### Task
- Collaborate with @wonilsuhibm for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Publish the page with markdowns.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/carbon-for-ibm-website #15](https://github.com/carbon-design-system/carbon-for-ibm-website/issues/15) via [**ZenHub**](https://www.zenhub.com/)
