### ISSUE TITLE
Page layout pattern study and design

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#678]
#### User Story

> As a `[user role below]`:
user of ibm.com

> I need to:
As an adopter I need to see examples of good layout design

> so that I can:
create a strong user flow and page narrative

https://ibm.box.com/s/iqapt5viffo3ha69nh2i5bwx5wbj9tr2

#### Tasks
 - [ ] Review past layout explorations and narrow down best examples
 - [ ] Continue explorations
 - [ ] Refine visual design treatment
 - [ ] Package up and prepare for documentation 

#### Acceptance criteria
 - [ ] Wonil reviews page layouts
 - [ ] Page layouts support web simplification templates (where possibile)
 - [ ] Page layouts support many patterns
