### ISSUE TITLE
Write page layout pattern guidelines

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#679]
#### User Story

> As a `[user role below]`:
user of ibm.com

> I need to:
As an adopter I need to see examples of good layout design

> so that I can:
create a strong user flow and page narrative

https://ibm.box.com/s/iqapt5viffo3ha69nh2i5bwx5wbj9tr2

#### Tasks
 - [ ] Document page layout design decisions and usage guidelines
 - [ ] Write guidelines for adopters to use
 - [ ] Collaborate with Jenny 

#### Acceptance criteria
 - [ ] Guidelines can be added to cupcake website and/or Carbon's site
 - [ ] The website publishing issue is created

**Comment by larahanlon2** [comment]
Closing this issue because it is a duplicate of https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/288
