### ISSUE TITLE
Collect layout pattern examples for gallery

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#698]
As an adopter of layout patterns, I need to see examples of patterns in use so I can decide which pattern suits my needs.

#### Additional information
- This story is building on the [layout patterns overview page](https://ibm-dotcom-library.mybluemix.net/patterns) for cupcake website
- Refer to [IDL layout page](https://www.ibm.com/design/language/layout/overview/) for examples of layouts they use

#### Tasks
- [ ] Collect layout patterns from Web Simplification Learn page
- [ ] Collect layout patterns from Cloud, Watson
- [ ] Collect layout patterns from other adopters (Originals, .org etc)
- [ ] Provide website team with assets to create a gallery on layout patterns overview page

**Comment by wonilsuhibm** [comment]
@larahanlon2 is this story still valid?

**Comment by larahanlon2** [comment]
@wonilsuhibm hmmm I'm not really sure what the original intent of this issue was. Do you remember when you created it? If not, we did talk about adding a gallery of layout patterns on the layout overview page. We could use this issue for some of that work?

**Comment by wonilsuhibm** [comment]
@larahanlon2 Yes, I think that was the intent — collect to feed into the gallery. Can you fill out the blank with how you think we should go about doing this please? (Sorry, I think I was responding to a comment from either Mike and Elliott and created this on the fly)

**Comment by larahanlon2** [comment]
@wonilsuhibm take a look at the updated issue title and description and let me know if it makes sense.

**Comment by wonilsuhibm** [comment]
@larahanlon2 so fast! and looks good. Thank you.
