### ISSUE TITLE
Cupcake website – review lead space documentation 

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#740]
#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the components, patterns, etc

> so that I can: do my day to day work without confusion.

#### Task
- [x] Jill to review lead space for content guidance.
- [x] Lara, Jenny etc. to share lead space with Carbon for feedback and alignment
- [ ] Jim review copy and provides edits if necessary

#### Acceptance criteria
- [ ] Wonil and Linda accepts/rejects all reviewers comments

**Comment by larahanlon2** [comment]
@JennySanchez FYI!

**Comment by larahanlon2** [comment]
Latest `Lead space: left-aliged` guidelines here: https://ibm.ent.box.com/notes/528552262380

- [ ] Made updates in response to Wonil's feedback in sprint 22
- [ ] Shared with Jill and incorporated her notes and feedback where applicable 
- [ ] Added new images for do's and don'ts
- [ ] Added new spec images

Still need to add image breakpoint notes.

**Comment by wonilsuhibm** [comment]
I added a suggestion for the intro paragraph:
```
A lead space is positioned at the top of a web page and serves as the first site of viewer engagement; its primary purpose is to orient the user when they land on a page and to help them decide whether to continue reading or not as well as orient themselves. This addresses one of the most important moments in the user's journey through a complex web environment.
```

**Comment by larahanlon2** [comment]
This is great, thanks so much @wonilsuhibm !

Do you think Jenny and Jacob can start porting this content into Gatsby? I think it would be helpful for us to see it live for a fresh perspective.

**Comment by larahanlon2** [comment]
> I added a suggestion for the intro paragraph:
> `
> A lead space is positioned at the top of a web page and serves as the first site of viewer engagement; its primary purpose is to orient the user when they land on a page and to help them decide whether to continue reading or not as well as orient themselves.
> 
> When designed and implemented effectively, the lead space can be used to engage visitors immediately in one of the most important moments in the user's journey through a complex web environment. It is the first full-width section below the masthead and can include a stylized background, headline, supporting message and call to action to accommodate user needs. 
> `

Hey @wonilsuhibm I see your suggestion to merge the into and overview in the [guidelines](https://ibm.ent.box.com/notes/528552262380). MY only comment is that we're following Carbon's content template which asks for:
1. Include a short description of your pattern ->This header should be longer than one line and no longer than four.
2. Define the use of your pattern with a problem statement. Explain a user's needs and how the pattern meets those needs. Communicate anything a designer needs to know about the pattern.

That is why I split the content into two sections: intro + overview. We have deviated a little from their template so if you're ok with deviating a little more we can make that change.

**Comment by larahanlon2** [comment]
@jacobottesen-dgc @JennySanchez I chatted with Wonil and he's good to publish what we have right now! We may need to refine and edit once we see it in Gatsby but please go ahead with the content in [Boxnote](https://ibm.ent.box.com/notes/528552262380). Thanks!

**Comment by JennySanchez** [comment]
Got it. Thanks @larahanlon2 .
