### ISSUE TITLE
Component: image - with caption - Prod ready

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#746]
### User story
As I go through various IBM pages, I would love to view images presented in a standard way which will allow me to view the image in the best way (appropriate resolution and aspect ratio in the given browser size and device screen size, screen reader, informative caption, etc).

### Notes
- This component will be used as the primary way of embedding images on pages.
- This component will be used as a trigger for the lightbox media view component.  Development of this functionality will be included in a later phase
- The first adopter of this component will most likely be used by the Web Simplification team.
- The Image Box folder is [here](https://ibm.box.com/s/zaofzs8ssrfbkgker2lqxyvdnbpxvsly)

### Acceptance criteria
- [ ] A way to choose one of the standard aspect ratios (1x1, 2x1, 16x9, 4x3) is provided
- [ ] A way to set different images for different breakpoints
- [ ] A way to set different images for different screen resolutions
- [ ] A way to change aspect ratio based on breakpoint
- [ ] A way to set caption
- [ ] Accessibility requirements are met

### Additional notes
![Screen Shot 2019-11-27 at 9 37 52 AM](https://user-images.githubusercontent.com/30183447/69732433-9b804f80-10f9-11ea-917c-2e50c2626305.png)

**Comment by photodow** [comment]
@RobertaJHahn I talked to @wonilsuhibm today, and it sounds like issues #699 and #767 should probably be apart of this epic. Talking it through the embeddable image component is essentially the same thing as the responsive image component just with a larger scope.

**Comment by RobertaJHahn** [comment]
@ljcarot This epic was not included in the original component list.  We have added the component to the Web Simplification MVP scope.  This epic was originally written with the Lightbox in scope.  We think that it is not since it isn't included in the pattern and component Airtable for the Learn page template.  Can you verify?  cc:  @jeffchew @photodow

**Comment by ljcarot** [comment]
So you want me to verify that "Image with caption" is in scope for Learn Page MVP and "Image with caption and viewer (lightbox)" is not in scope for MVP?

**Comment by RobertaJHahn** [comment]
@ljcarot yes, that is correct.

**Comment by ljcarot** [comment]
I got confirmation on call today with Web simplification that Lightbox on the Image Component is NOT required for MVP of Learn Page.  So focus of this issue is only Image Component with Caption.
