### ISSUE TITLE
Component: Create image - with caption design specs

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library#748]
As an adopter or developer on the DDS team I need to know the design specs for `image - with caption` pattern. Currently, the only documentation we have is dev/code.

### Tasks

- [x] Create a Sketch file with image - with caption design and specs
- [x] Create Box folder for image - with caption (if not already there)
- [x] Add design specs and Abstract version to Box folder 
- [x] Update any links or documentation that needs image - with caption specs

**Comment by RobertaJHahn** [comment]
@larahanlon2 I have changed this issue to be the same as Button Group (#1116).  Based on the conversations earlier today, I believe this work has to be done.

**Comment by larahanlon2** [comment]
Specs for `image with caption` complete and added to [Box](https://ibm.box.com/s/dtn9t9o1iy8h26rb66mr05gns98v42st) + [Abstract](https://share.goabstract.com/a1c3dc33-bc5a-4e4a-9b9f-5b2f5c31660a?).

@photodow you might need to update the func specs doc? Not sure.

**Comment by larahanlon2** [comment]
README added [here](https://ibm.ent.box.com/notes/610982526366).

**Comment by wonilsuhibm** [comment]
@larahanlon2 this looks great. Thank you. One QQ: should the focus border be 3 px like other buttons? And should there be inner white border fo a11y?

**Comment by larahanlon2** [comment]
@wonilsuhibm thanks. All buttons have 2px border, not 3px. Unless something has changed from Carbon? I think the white inner border works when the button is one color i.e all blue. In that case the white border is needed to separate the focus outline and the default button background. like so:
<img width="213" alt="Screen Shot 2020-02-04 at 10 15 20 AM" src="https://user-images.githubusercontent.com/53093550/73757465-45520d00-4737-11ea-9833-3d04a4551169.png">

But I'm not sure we need that inner border for this button because the blue outline already contrasts with the dark button background and the white search icon. With:
<img width="228" alt="Screen Shot 2020-02-04 at 10 12 23 AM" src="https://user-images.githubusercontent.com/53093550/73757574-674b8f80-4737-11ea-87f7-9209cbf9847b.png">

without:
<img width="227" alt="Screen Shot 2020-02-04 at 10 16 30 AM" src="https://user-images.githubusercontent.com/53093550/73757599-716d8e00-4737-11ea-86aa-d97e0c388dcf.png">

I prefer without the white inner border but if it's an a11y requirement of you want it to be I can make the change.

**Comment by wonilsuhibm** [comment]
@larahanlon2 I see that the design kit uses 2px border while their storybook is coded with 3px borders. I asked on the `#carbon-design-system` channel. Let's see what they say.

As for the while inner border, it is necessary because the blue and the dark gray bg are not discernable enough.

**Comment by larahanlon2** [comment]
@wonilsuhibm ok cool I'll add the white border and wait for Carbon's response.

**Comment by wonilsuhibm** [comment]
@larahanlon2 Thank you. Lauren from Carbon says it's supposed to be 2px. Let's go with 2.

**Comment by photodow** [comment]
@larahanlon2 I need to create the functional specs for this this sprint.

**Comment by photodow** [comment]
@larahanlon2 is that magnifying glass button different from the icon only buttons from carbon?
