### ISSUE TITLE
Cupcake website: update Layout patterns overview page

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library#793]
> As an adopter 

> I need to know what layout patterns are, what patterns are available to adopt, and what is coming soon

> so that I can understand how and when to use the different patterns.

#### Tasks
 - [x] Lara to provide updates to layout patterns overview (intro)
 - [x] Lara to provide updates to upcoming layout patterns (table list)
 - [x] Lara to provide images of layout patterns to illustrate the principles and application of layout to ibm.com patterns

#### Acceptance criteria
 - [ ] Guidelines can be added to cupcake website and/or Carbon's site
 - [ ] Jenny and Jacob can make the changes on Gatsby within the timeframe
 - [ ] Wonil and Linda accept the updates

**Comment by larahanlon2** [comment]
Hey @JennySanchez do you think we could make the following changes to the Layout patterns [Overview](https://carbon-for-ibmdotcom.netlify.com/patterns) page, please?

1. Remove **Content array**, **Simple long form**, and **Use cases** from the left nav:
<img width="301" alt="Screen Shot 2019-12-09 at 10 07 29 PM" src="https://user-images.githubusercontent.com/53093550/70492186-99db6200-1ad1-11ea-8a6f-3dddb92d286b.png">

2. Update the `IBM.com layout patterns` table on the Overview page to the following. Let's drop the **Descriptions** for now and only have the **Pattern name** and **Status**:

- Lead space – left-aligned | available
- Lead space – centered | coming soon
- Logo grid | coming soon
- Rich overview | in progress
- Simple array | coming soon
- Simple benefits | coming soon
- Simple long-form | coming soon
- Simple overview | coming soon
- Testimonials | in progress
- Use cases | coming soon

**Comment by jacobottesen-dgc** [comment]
@larahanlon2 Just made updates to the based on the request directly above. Live link here: https://deploy-preview-168--carbon-for-ibmdotcom.netlify.com/patterns

cc. @JennySanchez

**Comment by JennySanchez** [comment]
@larahanlon2 The updates are completed. The live page can be viewed [here](https://deploy-preview-168--carbon-for-ibmdotcom.netlify.com/patterns/).

**Comment by larahanlon2** [comment]
@jacobottesen-dgc @JennySanchez 

### Hey. Here is the updated content for the Overview intro paragraph.

<img width="1620" alt="Screen Shot 2019-12-10 at 4 46 46 PM" src="https://user-images.githubusercontent.com/53093550/70572030-f93a8000-1b6c-11ea-9a53-4033d8f7d61c.png">

**Update to:**
Layout patterns show the many ways in which content can be arranged using the 2x grid. They are used to render prescribed content types in different ways, in response to user needs. Layout patterns help to form the appropriate page structure and user flow in a visually pleasing manner and are authorable by a CMS user.

**Comment by larahanlon2** [comment]
As per quick Slack discussion, can we please remove this second card. We no longer need it as we will add all guidelines for layout to the overview page. Thanks!

<img width="907" alt="Screen Shot 2019-12-10 at 6 02 34 PM" src="https://user-images.githubusercontent.com/53093550/70578423-ab794400-1b7b-11ea-8509-a7e946714429.png">

**Comment by larahanlon2** [comment]
Can the table titles also be updated, please. Let's change:
– **IBM.com layout patterns => Layout patterns**
– **Layout patterns => Name**
– Lease **Status** as is

<img width="1063" alt="Screen Shot 2019-12-10 at 6 38 53 PM" src="https://user-images.githubusercontent.com/53093550/70579075-8be31b00-1b7d-11ea-8372-08fefbd1aad1.png">

**Comment by jacobottesen-dgc** [comment]
@larahanlon2 Just finished the tasks above except for updating the Overview intro paragraph. 

cc. @JennySanchez

**Comment by RobertaJHahn** [comment]
@JennySanchez @larahanlon2 Can this issue be closed?

**Comment by larahanlon2** [comment]
@RobertaJHahn yes I will close now. There is a new issue open [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/244#issuecomment-571607469) for the next round of updates.

**Comment by larahanlon2** [comment]
Feedback from IDL / Carbon review, Thurs 9th Jan.
—


**Purpose** 
- This is a good section
- May not need visual schematics. They might be too confusing and prescriptive. 
- Consider just expressing the point in words.
- Be more high level in the guidance
- Consider: Editorial, Navigational, Messaging, Transactional
- Future goal to include more practical guidelines and resources 
- Mike: Is “reading” too abstract. Is it more “editorial” or “storytelling”. Need to get the intent for the user. 
- Elliott: need to include language around templates. Those templates meet the needs of the different page purposes. Direct adopters to use them. If the templates do not work/exist THEN the designers should design as per purpose.
- Be clear on who this is all for.


**2x Grid** 
- Add grid lines to show the vertical rhythm between the two examples



**Hierarchy** 
- Consider “content" hierarchy 
- For page level hierarchy examples consider Watson homepage 



**Next steps** 
- Take a step back
- Focus on patterns and move upward from there
- Focus on pattern level details and purpose
- Stacking and relationship with other patterns
- How they work together to form different types of pages
- Follow and use IDL layout [tips and techniques](https://www.ibm.com/design/language/layout/tips-and-techniques) content and images (eg. Watson patterns)
