### ISSUE TITLE
Review expressive components and document updates for developers

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#799]
#### User Story

> As a `[user role below]`:

Designer on the Carbon for IBM.com team

> I need to:

document what needs to be updated in the themed components

> so that 

the developers can match the coded components to design intent.

#### Additional information

Here is the list of prioritized components from Search and Commerce squad #521 that should be reviewed and developed first.

**Consolidated list of components, items 1–10 are needed by both teams.**
 
- [x]  buttons
- [x]  links
- [x]  tabs
- [x]  checkbox
- [x]  pagination
- [x]  modals
- [ ]  tags
- [x]  search
- [ ]  horizontal rule (dotcom library)
- [x]  tooltip

---

- [x]  accordion
- [ ]  dropdown
- [ ]  form
- [ ]  icon button
- [ ]  loading
- [x]  text input
- [ ]  content switcher
- [ ]  progress indicator
- [x]  list
- [ ]  notification
- [ ]  overflow menu
- [x]  tile
- [ ]  Shell or left panel (dotcom library)
- [ ]  data table
- [ ]  pagination
- [x]  number input
- [ ]  radio button
- [ ]  structured list

**All other components**
- [ ] breadrumb
- [ ] code snippet
- [ ] date picker
- [ ] time picker
- [ ] file uploader
- [ ] inline loading
- [ ] list
- [ ] loading
- [ ] select
- [ ] slider
- [ ] toggle
- [ ] UI shell header
- [ ] UI shell left panel
- [ ] UI shell right panel
 

#### Acceptance criteria
 - [ ] Issues created for individual component and variants
 - [ ] Any issues not reviewed within sprint 24 are carried over in a new issue in the first sprint in 2020

**Comment by oliviaflory** [comment]
This epic is a duplicate and will be closed in favor of #822
