### ISSUE TITLE
Expressive theme

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library#822]
This epic is to track the design review and updates for the expressive theme

Here is the list of prioritized components from Search and Commerce squad #521 that should be reviewed and developed first.

---

#### User Story

> As a `[user role below]`:

Designer on the Carbon for IBM.com team

> I need to:

document what needs to be updated in the themed components

> so that 

the developers can match the coded components to design intent.

#### Additional information

Here is the list of prioritized components from Search and Commerce squad #521 that should be reviewed and developed first.

**Consolidated list of components, items 1–10 are needed by both teams.**
 
- [x]  buttons
- [x]  links
- [x]  tabs
- [x]  checkbox
- [x]  pagination
- [x]  modals
- [ ]  tags
- [x]  search
- [ ]  horizontal rule (dotcom library)
- [x]  tooltip

---

- [x]  accordion
- [x]  dropdown
- [x]  form
- [ ]  icon button
- [x]  loading
- [x]  text input
- [x]  content switcher
- [x]  progress indicator
- [x]  list
- [x]  notification
- [x]  overflow menu
- [x]  tile
- [ ]  Shell or left panel (dotcom library)
- [x]  data table
- [x]  pagination
- [x]  number input
- [x]  radio button
- [x]  structured list

**All other components**
- [x] breadrumb
- [x] code snippet
- [x] date picker
- [x] time picker
- [x] file uploader
- [x] inline loading
- [x] list
- [x] loading
- [x] select
- [x] slider
- [x] toggle
- [ ] UI shell header
- [ ] UI shell left panel
- [ ] UI shell right panel
 

#### Acceptance criteria
 - [ ] Issues created for individual component and variants
 - [ ] Any issues not reviewed within sprint 24 are carried over in a new issue in the first sprint in 2020

**Comment by RobertaJHahn** [comment]
All linked issues are closed.  Closing this epic.
