### ISSUE TITLE
[Card Array] Update with latest design specs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#830]
## Detailed description

In general the CardArray is off because it was based on outdated specs. I'll list out a few high level things to look out for, but in general we just need to go back to the correct specs and make sure it aligns. Then we can do another pass. There are two issues in particular if tackled first could reduce the size of this work.

> 👀 see #745 and #829  for help with many of this

- [x] **Spacing** issues (see #745 and #829  for help with many of this)
- [x] Cards should be **hanging**, and text within the card should align with that above.
- [x] **Grid** is off in a number of places (again #745 and #829 should help)
   - [x] the main title should be 8 columns
   - [x] lg < is off (just in general it's all off)
- [x] **Typography** is missing things like `max-width`, and `width` (again #745 and #829 should help)
   - all titles are missing things like `max-width`

### Additional resources
- [Design Specs](https://ibm.box.com/s/fx8odkidz7h63yh242p4k8wrtz77gxj1)
- [Functional Specs](https://ibm.box.com/s/px2557guu928pwu3umr71t255u409teu)

**Comment by RaphaelAmadeu** [comment]
This update is being done along with the updates on this PR: https://github.com/carbon-design-system/ibm-dotcom-library/pull/902
