### ISSUE TITLE
[Content block - mixed groups] Update list section story

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/ibm-dotcom-library#831]
## Detailed description

Right now the [ListSection story](https://ibmdotcom-patterns-react-experimental.netlify.com/?path=/story/list-section--default) (name pending) only accounts for the SimpleArray.

I think we should consider breaking out the SimpleArray like we've done with PictogramArray, and CardArray, create its own story, and then for list section using knobs pass in the different types of content groups.

## Additional information

- [ ] Break out SimpleArray into its own pattern and story
- [ ] Leverage shared components like the contentArrayGroup #745 
- [ ] Can we make the pictogram optional inside the pictogram entity, and use that here?
- [ ] Add a content group knob to the ListSection allowing you to add or remove different types of groups (e.g. CardArray, PictogramArray, SimpleArray)

**Comment by RobertaJHahn** [comment]
Closing this issue.  This approach has been incorporated into the ontology refactoring effort.   

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/ad4be0d8-adc1-416e-a82d-d4a95fd57de9)
