### ISSUE TITLE
Pattern:  Perform Featured Link gap analysis of the code, design and functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library#895]
#### User Story

> As a `[user role below]`:
DDS BA

> I need to:
review the design specs, functional specs and code 

> so that I can:
be sure that all are aligned and provide a quality experience for the designers and developers that use the ibm.com Library patterns and components to build their web sites.

#### Additional information

- [Design specs issue #659](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/659)
- [Functional specs issue #683](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/683)
 - [alpha dev issue #706](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/706)

#### Acceptance criteria
 - [ ] Gap analysis of alpha code and design & functional specs
 - [ ] If applicable, create and size stories for additional work

**Comment by RobertaJHahn** [comment]
@photodow @jeffchew Here is the separate issue for the gap analysis to be performed at the beginning of each sprint that the QA work is scheduled.  Take a look and make any changes you think are needed.  @photodow Do you want an estimate to be included with all of the gap analysis issues I create or would you like to add it later?

**Comment by photodow** [comment]
Here's what I have based on my gap analysis.

- [x] Update documentation (FeaturedLink, CardSection, Image) #1072
- [x] Icon button and placement #1071
- [x] High contrast theme (CardLink) #1070
- [x] Themable mixin #1069
- [x] Update FS data model #1068
- [x] Card needs to hang, so text aligns. #1067
